### ISSUE TITLE
Invisible failure after change in gmail password

### ISSUE THREAD

**Issue by kleinschmidt** [Foundry376/Mailspring#1178]
##### Are there any related issues?

#437 describes a symptom (endlessly "sending mails")

##### What operating system are you using?

Arch linux (kernel 4.18.16)

##### What version of Mailspring are you using?

1.5.0-2 (from Arch User Repository)

--

**Bug?**

##### Is this an email sync or connection issue?

Yes: silent error after change in password.  In the UI I see endlessly "syncing your mailbox" and "sending messages (N)".  But with green indicators on the affected account.  I had to go to the logs to see

```
11988 [2018-10-25 20:54:29.968] [background] [info] Fetching XOAuth2 access token from Gmail for 625bca97
11988 [2018-10-25 20:54:30.124] [background] [info] Sleeping after exception: {"debuginfo":"https://www.googleapis.com/oauth2/v4/token","key":"Invalid Response Code: 400","retryable":true,"what":"std::exception"}
```

I would expect an auth failure to show up as an error in the UI.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

It occurred with gmail but I didn't try changing my password on another account.

**Comment by kleinschmidt** [comment]
(in case it's not obvious, the immediate problem was solved on my end by re-authenticating the offending account.  the bug is that not surfacing the auth failure to the UI made it hard for me to figure out what should have been obvious, namely, that I needed to re-auth that account).

**Comment by calebsylvest** [comment]
Upvote from me on this issue.

Just experienced this silent failure for several days before figuring out what was wrong and re-authenticating my gmail account. Incoming and outgoing mail was stuck for days without knowing about it.

This should be labeled as a `bug`, though it's also a user experience problem.

---

_Auth broken but not known_
![screen shot 2019-01-15 at 11 28 20 am](https://user-images.githubusercontent.com/4457883/51198709-a56eda80-18ba-11e9-851e-573b3e399c46.png)

_Auth reconnected and syncing_
![screen shot 2019-01-15 at 11 32 16 am](https://user-images.githubusercontent.com/4457883/51198710-a7389e00-18ba-11e9-8b12-4f36993058fc.png)

**Comment by Nashluffy** [comment]
This is still happening, and I don't see a way to change the account's password either. Is the process to delete the account, which I can't even seem to find the button for either?

**Comment by Schparky** [comment]
I see the same thing. Didn't realize I wasn't getting emails on one account for several days. Even after re-authenticating, I had to restart Mailspring in order for it to start communicating with this account.

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Can anyone please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team
