### ISSUE TITLE
Unable to sync exchange account through Davmail

### ISSUE THREAD

**Issue by jose-sanchezm** [Foundry376/Mailspring#118]
##### Are there any related issues?
Not that I'm aware of
...
##### What operating system are you using?
elementaryOS Loki based on Ubuntu 16.04
...

##### What version of Mailspring are you using?
1.0.3, davmail version 4.8.0-2479
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A
...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

I'm accessing my exchange email account through davmail which works perfectly in Thunderbird. With version 1.0.3 at last I'm able to add the custom ports that I need. However, when it tries to sync the email it fails. This is the last error shown in davmail log:

6 BAD unable to handle request: Folder '[Mailspring]' not found

[mailsync-44aaf8cc.log](https://github.com/Foundry376/Mailspring/files/1374895/mailsync-44aaf8cc.log)

**Comment by jose-sanchezm** [comment]
Creating manually the folders in Thunderbird allows to pass this point but it fails sync anyway.

[mailsync-adf47009.log](https://github.com/Foundry376/Mailspring/files/1374923/mailsync-adf47009.log)

**Comment by casamanya** [comment]
Same issue for me!

Installed
[mailsync-169a95e7.log](https://github.com/Foundry376/Mailspring/files/1375252/mailsync-169a95e7.log)
 version 1.0.3 on ubuntu 17.04 with Davmail.

**Comment by bengotow** [comment]
This should be fixed in the next release - stay tuned.

**Comment by bengotow** [comment]
Hey! We just released 1.0.4 which I believe will address this issue—can you try it out and let me know? On Linux, you'll need to download it manually: getmailspring.com/download. (Linux `Snap` package with autoupdating should be ready by next week sometime!)

**Comment by casamanya** [comment]
Hello,

I've just updated to 1.0.4 and still have the problem. My Davmail version: 4.8.0.3-2488

[mailsync-169a95e7.log](https://github.com/Foundry376/Mailspring/files/1381734/mailsync-169a95e7.log)

**Comment by jose-sanchezm** [comment]
Same issue still happening.

[mailsync-79aec045.log](https://github.com/Foundry376/Mailspring/files/1381750/mailsync-79aec045.log)

**Comment by reubn** [comment]
Still happening in 1.0.6

**Comment by jeslago** [comment]
Still happening in 1.0.7.

**Comment by bengotow** [comment]
Hey folks, sorry for the delay on this one. It looks like these logs all point to a single issue (which is a nice change for once). It seems like Davmail may be reporting multiple IMAP folders with the exact same name, which breaks an assumption in Mailspring's sync engine that folder/namespace paths are unique. 

I can make Mailspring ignore duplicate folders, but I think there may be something more complicated going on here. Does anyone know if there's a way to get a sample Davmail account to test with? (Maybe there's a demo server?) Would make this a lot quicker to fix!

**Comment by edaelli** [comment]
I can reproduce this consistently and am willing to to do it on debug builds if you want to send them my way... Not sure a davmail + ews demo server exists.

**Comment by bengotow** [comment]
Hey folks - this has been fixed in the latest release (1.1.2) through #588. Cheers!

**Comment by jose-sanchezm** [comment]
Hello, I'm still getting errors due to duplicate folders and my mail does not appear on the application. It keeps on "Syncing your mailbox" and neither the folders nor the mails appear:

{ [Error: SyncWorker crashed with null (code 1)] message: 'SyncWorker crashed with null (code 1)' } { stack: '',
  rawMessage: 'Error: Account is missing required fields:imap_password or refresh_token',
  provider: 'imap',
  log: '31982 [2018-01-29 16:25:00.912] [background] [info] Marking all folders as `busy`\n31982 [2018-01-29 16:25:00.913] [background] [info] Syncing folder list...\n31982 [2018-01-29 16:25:00.913] [metadata] [info] Metadata delta stream starting...\n31982 [2018-01-29 16:25:05.662] [background] [critical] \n ***\n *** A C++ exception occurred during program execution: \n *** UNIQUE constraint failed: Folder.id\n ***\n\n31982 [2018-01-29 16:25:05.680] [background] [critical]  *** Stack trace (line numbers are approximate):\n *** (unknown)  clone\n ***\n\n32121 [2018-01-29 16:25:05.837] [main] [info] ------------- Starting Sync (jose.sanchezm@atos.net) ---------------\n32121 [2018-01-29 16:25:05.840] [background] [info] Marking all folders as `busy`\n32121 [2018-01-29 16:25:05.840] [background] [info] Syncing folder list...\n32121 [2018-01-29 16:25:05.840] [metadata] [info] Metadata delta stream starting...\n32121 [2018-01-29 16:25:10.649] [background] [critical] \n ***\n *** A C++ exception occurred during program execution: \n *** UNIQUE constraint failed: Folder.id\n ***\n\n32121 [2018-01-29 16:25:10.668] [background] [critical]  *** Stack trace (line numbers are approximate):\n *** (unknown)  clone\n ***\n\n' }

**Comment by jose-sanchezm** [comment]
I was using an outdated version but removing it, removing the .config/Mailspring folder and then installing 1.1.2 I'm getting a similar error in the logs. The log file is attached.
[mailsync-79aec045.log](https://github.com/Foundry376/Mailspring/files/1677129/mailsync-79aec045.log)

**Comment by edaelli** [comment]
Works for me! Thanks!

**Comment by kevinsarsen** [comment]
Please reopen this ticket. This isn't fixed for me using v1.5.6-4cb1851b. Excerpt from log:

```
28474 [2019-02-20 10:16:18.674] [main] [info] Identity created at 1549060724 - using ID Schema 1
28474 [2019-02-20 10:16:18.675] [main] [info] ------------- Starting Sync ([redacted]) ---------------
28474 [2019-02-20 10:16:18.678] [background] [info] Marking all folders as `busy`
28474 [2019-02-20 10:16:18.678] [background] [info] Syncing folder list...
28474 [2019-02-20 10:16:18.678] [metadata] [info] Metadata delta stream starting...
28474 [2019-02-20 10:16:19.104] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** UNIQUE constraint failed: Folder.id
 ***

28474 [2019-02-20 10:16:19.125] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***
```

**Comment by kevinsarsen** [comment]
will open new issue.
