### ISSUE TITLE
CTRL+Q to "mark as read"

### ISSUE THREAD

**Issue by shawnkhall** [Foundry376/Mailspring#1227]
##### Are there any related issues?
No

...

##### What operating system are you using?
Windows 10
...

##### What version of Mailspring are you using?
1.5.2
...

--

**Bug?**

##### Is this an email sync or connection issue?
No.

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Reproducible in all mail contexts.

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Yes. The basic "mark as read" key combination is not available in Mailspring. CTRL+Q (aka "mod+q" in Mailspring) is the shortcut in Outlook. Mailspring allows me to set the "mark as read" shortcut to "mod+q" under settings, but when pressing CTRL+Q in the standard Mail view it closes Mailspring. This is a behavior that will make it impossible to switch from Outlook, since this keyboard shortcut is second-nature.
...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—wow, I didn't know about that one! I think you're right that Ctrl-Q is incorrectly permanently tied to "Quit Mailspring" because that's the standard "exit program" shortcut on macOS. I'll get this fixed in the next release.

**Comment by bengotow** [comment]
Hey! The fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!

**Comment by hktegner** [comment]
This is still an issue for me in v1.7.2-4522b259. I'm on Ubuntu Linux 18.04.

**Comment by KristianI** [comment]
Also, still issue on windows version v.1.7.8.

I changed the shortcut to workaround it.

**Comment by rog1039** [comment]
I am on Windows on version 1.7.8 as well. Tried changing the "Mark as Read" shortcut to Control+Q (aka Mod+q). The program accepted the new shortcut, however Control+Q still closes Mailspring rather than marking the email as read.

Thanks!

**Comment by aia832003** [comment]
This is still an issue with the current version on Fedora, Windows, and Ubuntu. Version 1.80 still closes the app even after altering the shortcut.

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/ctrl-q-closes-program-instead-of-marking-mail-as-read-with-outlook-shortcuts/940

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team
