### ISSUE TITLE
Crashes on Ubuntu 17.04

### ISSUE THREAD

**Issue by ldartez** [Foundry376/Mailspring#14]
Mailspring 1.0 debian package mailspring-1.0.0-amd64.deb. The program installed without any problems. Every time the program is started an error dialog pops up with a message about my local email database (screenshot attached). Clicking 'okay' closes the window but the same window pops back up indefinitely. I had to use sigkill to stop the process each time.

![screenshot from 2017-10-04 01-32-54](https://user-images.githubusercontent.com/1535292/31162619-251da118-a8a4-11e7-822d-df78082c5591.png)

```
            .-/+oossssoo+/-.               louis@xi
        `:+ssssssssssssssssss+:`           --------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 17.04 x86_64
    .ossssssssssssssssssdMMMNysssso.       Model: Blade 6.06
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.10.0-35-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 8 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2212
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.7
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Unity:Unity7
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Compiz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Ambiance
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Ambiance [GTK2/3]
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Ubuntu-mono-dark [GTK2/3]
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: x-terminal-emul
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-7700HQ (8) @ 3.8GHz
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel Kabylake GT2
      -+sssssssssssssssssyyyssss+-         GPU: NVIDIA GeForce GTX 1060 Mobile
        `:+ssssssssssssssssss+:`           Memory: 3149MiB / 15932MiB

```

**Comment by sylvaindumont** [comment]
It may come from installation errors:
```
Setting up mailspring (1.0.0) ...
Usage: lsb_release [options]

lsb_release: error: no such option: -u
Usage: lsb_release [options]

lsb_release: error: no such option: -u
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-1) ...
```

**Comment by LiamDawe** [comment]
Yep, exactly the same here. If you need more details let me know. Can provide anything needed.

**Comment by nikaro** [comment]
Same for me on Ubuntu 17.10. And i also have `lsb_release` error.

**Comment by nikaro** [comment]
It does not seem to be linked to the `lsb_release` error. I added the `-u` option to `/usr/bin/lsb_release` (doing the same thing that `-a`), purged Mailspring and reinstalled it. Still does not work.

**Comment by Pegasuz** [comment]
Same error here.

**Comment by gocarlos** [comment]
This also happens with ubuntu 14.04

**Comment by ajvn** [comment]
Same happens on Fedora 26, installation goes without errors.

**Comment by lenarddome** [comment]
Same error here.

**Comment by severin-lemaignan** [comment]
+1

**Comment by jose-sanchezm** [comment]
Same on elementaryOS Loki (Ubuntu 16.04)
Is there ANY distribution in which it works?

**Comment by ToxicDragon** [comment]
Same on KDE Neon (Ubuntu 16.04)

Proper verbose output would be nice (the log file is quite scarce)

**Comment by CicoZhang** [comment]
Same here on Ubuntu 17.04 (Gnome)

**Comment by letic** [comment]
Tried the dev mode (-d) but results are the same. 

Logs doe not give any information on the reason :
 ```
{"host":"xxxxxx","timestamp":"2017-10-04T15:20:45.859Z","payload":"App load time: 376ms\n"}
/tmp/Nylas-Mail-15145.log (END)
```

**Comment by LukeStephen** [comment]
I get the same error message

**Comment by mshallop** [comment]
Ubuntu 16.04 gnome - same issue.
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by bengotow** [comment]
Hey folks! Thanks for checking out Mailspring—the Linux version actually hasn't been released yet ( where did you find a download link? I hope I didn't leave it turned on...) 

The linux version should be ready in the next few days—I had to change the way the C++ mailsync codebase is compiled to link against linux dependencies in a more portable way. Stay tuned!

**Comment by severin-lemaignan** [comment]
I found the news + link here: http://www.omgubuntu.co.uk/2017/10/mailspring-nylas-fork-released

**Comment by ldartez** [comment]
@bengotow i detailed how i found the download link in the comments of issue #11

**Comment by bengotow** [comment]
Ahh haha excellent - thanks for letting me know! Guess there are pros and cons to descriptive error messages ;-)

**Comment by cobisimo** [comment]
It looks like install script does not download sync binary. You can download it manually from:
https://mailspring-builds.s3.amazonaws.com/client/01295136/linux/mailsync.tar.gz
and extract its content to `/usr/share/mailspring/resources/app.asar.unpacked`

**Comment by paulocoghi** [comment]
@bengotow Here, the 1.0.1 deb version is working perfectly in my Ubuntu 16.04. Can I inform it to the OmgUbuntu author?

**Comment by alexfalcucc** [comment]
@bengotow weird, 1.0.0 deb version it's working fine for me on Ubuntu 14.04.

**Comment by ldartez** [comment]
with @cobisimo's comment I was able to get v1.0 to run on my machine. I have no upgraded to the v1.0.1 deb package. I am able to sign in to my gmail account. (But i'm unable to connect any of my Exchange accounts.)

**Comment by berkiyo** [comment]
I am also getting the same issue on Windows 10. 
![capture](https://user-images.githubusercontent.com/16160502/31218392-e2b99224-aa05-11e7-92a4-73051bf1d1a0.JPG)

**Comment by cynddl** [comment]
When installing from scratch, the error seems to happen because the ```app/mailsync.tar.gz``` file is downloaded during postinstall, but not unpacked. Extracting the archive solves the spawn ENOENT issue.

**Comment by bengotow** [comment]
Ahh thanks @cynddl — we should definitely catch the error and display a better message if it's an `ENOENT` and you just need to unpack the mailsync archive!

**Comment by bengotow** [comment]
Hey folks the `lsb_release` error should be fixed in 1.0.3 and I've improved the error message to mention the .tar.gz file if you get an ENOENT. (f7808777a7369a7a6b7c0f3e23ddb9e5d4eec957). Will close this when the next version ships.

**Comment by zephinzer** [comment]
facing the same issue, looked into the `./scripts/postinstall.js` and reconstructed the URL manually and cURLed it with:

```sh
curl -vv -sSLo ./app/mailsync.tar.gz "https://mailspring-builds.s3.amazonaws.com/client/1.2.1-7e7447b6/linux/mailsync.tar.gz"
```

it came back with a 403 forbidden which i suppose is the reason the `npm i` command fails :/ the link which @cobisimo provided also returns an AccessDenied from s3

**Comment by EzioRaison** [comment]
Hi All, I'm getting the same issue on Windows, tried uninstalling and reinstalling still the issue persists.
![image](https://user-images.githubusercontent.com/36783722/158165942-15843940-8163-48b6-915a-1253bf25e10b.png)
