### ISSUE TITLE
Add gtk-3-themes plug in the snap

### ISSUE THREAD

**Issue by JackHack96** [Foundry376/Mailspring#1435]
**Feature Request?** Yes

Hi! Thanks for this beautiful project, using it since last year and working great so far!

Would it be possible to add the `gtk-3-themes` plug and the `icon-themes` plug in the snap? So it becomes possible to use themes (at least those who have been snapped).
I understand there are plenty of other issues, much more important than this feature request, so this is not a priority :+1:

**Comment by bengotow** [comment]
Oh definitely—this seems like a quick fix. I'll change the snapcraft.yml and kick off an `edge` build you can take for a spin. 👍

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Comment by johanneskoester** [comment]
Hey, mailspring 1.7.2 still does not seem to use the ubuntu GTK theme. Am I doing something wrong?

**Comment by johanneskoester** [comment]
For example the file save dialog uses the adwaita theme instead of yaru.

**Comment by dastorm** [comment]
I can confirm this. Comparing the yaml file with [this](https://github.com/snapcrafters/gimp/blob/master/snap/snapcraft.yaml) for gimp (that is correctly themed) I see they use a  gnome-3-28-1804 plug too. Maybe that's what's missing?
