### ISSUE TITLE
Calendar preview only shows empty screen

### ISSUE THREAD

**Issue by mslourens** [Foundry376/Mailspring#1492]
**What operating system are you using?**
Linux Mint 19.1

**What version of Mailspring are you using?**
1.6.1

**Steps to reproduce:**
*Prerequisites:* Create GMail account

1. Click Developer -> Calendar Preview
2. An empty calendar window opens (without any chrome, like a close button)

**Way to fix the bug**
I've cloned the repository and debugged the application. There are two reasons the Calendar Preview window is empty:

1. The file ``calendar-wrapper.ts`` (in interal_packages/main-calendar/lib/core) is importing the class ``MailspringCalendar`` from ``'./core/mailspring-calendar';`` (on line 8), but there is no file called mailspring-calendar.tsx. You have to rename nylas-calendar.tsx to mailspring-calendar.tsx (or change the import).
2. The file ``calendar-toggles.tsz`` (in interal_packages/main-calendar/lib/core) is checking for ``disabledCalendars`` to contain the current ``calendar.id`` but the prop is undefined. To fix this issue you have to either check if the property exist or give it an empty value in the config (where it comes from).

**Comment by bengotow** [comment]
Hey @mslourens—wow, thanks for reporting this! It looks like I broke this right at the end of the typescript conversion by renaming a few things. I'll get this fixed in the next release! I've been working on the sync logic for the calendar feature and the preview should be getting more fun soon - stay tuned!

**Comment by ransagy** [comment]
@bengotow This still happens on 1.6.2 for me - None of my 3 gmail accounts (one is a gapps/gsuite work account) show anything on the preview screen.

**Comment by mslourens** [comment]
fixed by version 2.6.2 for me

**Comment by ransagy** [comment]
@mslourens did you mean 1.6.2?

Either way, Still the same for me on 1.6.3. The sidebar loads and shows the various event categories, but nothing actually appears in the calendar itself.

**Comment by mslourens** [comment]
@ransagy Yes, I meant 1.6.2, sorry about the confusion. 
Do you see any errors in the developer tools, if you open them by going to Developer => Toggle Developer Tools or press CTRL+ALT+I?

**Comment by ransagy** [comment]
Nope, first thing i checked. Just debug info about querying the event data store.

**Comment by bengotow** [comment]
Hey folks—thanks for the updates here. It looks like we've gotten some automated JS exceptions reported from the calendar preview in the latest release, so I'll see if I can get this fixed. Starting in the next month or so you'll be able to create / edit calendar events as well and this should get a whole lot more polished. Stay tuned!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in a recent release and 1.7.6, which shipped today, should leave things in a nice stable place while I go and finish the calendar feature. Stay tuned!

**Comment by keith-collyer** [comment]
For me, the calendar preview shows a list of my Google calendars, but the calendar itself is blank.
Mailspring 1.9.2-6e14dad1
Windows 10 Home 21H2 build 19044.1466

**Comment by keith-collyer** [comment]
The main display is out of sync with the mini-calendar showing the month when I Maximize the window, it's fine in the normal size. So right now the mini-calendar is showing the month of January, with today (25) highlighted. The main display shows that week starting on Sunday, the same as the mini-calendar, with today highlighted. When I maximize, the mini-calendar stays the same, but the main display now shows a week ending on the 25th - actually only part of the day, and the left-hand end has part of the previous Tuesday showing.
Mailspring 1.9.2-6e14dad1
Windows 10 Home 21H2 build 19044.1466
