### ISSUE TITLE
Notifications for incoming mail not working

### ISSUE THREAD

**Issue by ReekyMarko** [Foundry376/Mailspring#160]
As the title says, notfications are not working when an email comes to my inbox. Weirdly, the "opened" notifications do work. I'm on Arch Linux and using KDE as my DE.

**Comment by bengotow** [comment]
That is super odd... is there any chance the email is from you? It's a little odd, but I'm looking at the code now and it seems to specifically not notify you about unread email from yourself: https://github.com/Foundry376/Mailspring/blame/master/app/internal_packages/unread-notifications/lib/main.es6#L51

**Comment by ReekyMarko** [comment]
That might be it, because I was sending test mails back and forth to my own accounts, but I'm 99% sure I haven't seen any notifications from other emails either since I switched from Nylas to Mailspring.

**Comment by Tornado-Tim** [comment]
I can also confirm this issue, no notifications, on Fedora 26 with Gnome, made sure all necessary library's where installed.

**Comment by bengotow** [comment]
Thanks - we should definitely investigate whether something else needs to
be installed. The notifications use Electron / Chromiums web Notification
API.

**Comment by mamantoha** [comment]
Same here on KDE neon(based on Ubuntu 16.04) with Plasma 5.11

**Comment by domenico-ruggiano** [comment]
Same problem in **Windows 10** for me

**Comment by mamantoha** [comment]
I can confirm that it fixed in 1.0.6

**Comment by Tornado-Tim** [comment]
Yup issue fixed :) Thanks @bengotow :)

**Comment by areebaliasr** [comment]
Notifications not showing in current version

**Comment by JuanRaymundo** [comment]
I can't know when I receive emails

**Comment by VladimirMikulic** [comment]
I have also the same problem. Desktop notifications for incoming emails don't show up.

**Comment by VladimirMikulic** [comment]
Fixed it. @areebaliasr & @JuanRaymundo make sure that you have **Zenity** installed. Stupid mistake, I know :)

**Comment by gonced8** [comment]
I just installed the app with snap and have Zenity installed, however, notifications still don't work

**Comment by anas9244** [comment]
I have zenity installed and still no notification on Ubuntu 19.4

**Comment by wizardion** [comment]
+1 on Ubuntu 19.04 in my case it Unity, when the app is closed (in tray), notifications are not showing. When the app is active (opened window) - notifications are showing.

**Comment by atistrcsn** [comment]
I have zenity installed too on Debian 9 and no notification either.
Mailspring snap version: 1.6.1.aceed8e5

**Comment by VladimirMikulic** [comment]
So, I've tested this behaviour on my PC and I've found out something strange. Mailspring's notifications appear when I use native Plasma dock(I am running Kubuntu), but when I use latte-dock or any other dock, notifications don't work.
