### ISSUE TITLE
No Google contacts?

### ISSUE THREAD

**Issue by ghost** [Foundry376/Mailspring#1709]
Opening **Window > Contacts**, the only contacts listed are those "Found in Mail".  None of my Google Contacts are available, nor do they autocomplete when composing a new message.

##### Are there any related issues?

It is my understanding that with [[Feature Request] Address Book](https://github.com/Foundry376/Mailspring/issues/86), I should be able to see all my contacts, but not be able to modify them.

...

##### What operating system are you using?

This occurs both on Windows 10 and Linux Mint 19.2
...

##### What version of Mailspring are you using?
(1.7.2-4522b259)

--

**Bug?**

This appears to be a bug. All my mail is there, just not any contacts other than those from messages in my Sent folder.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Gmail

...

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Every other email client I use eM Client, Thunderbird (using gContactSync extension) Windows 10 Mail app provides at least read-only access to my Google Contacts. Without them, Mailspring is basically useless for me.

...

I'd be happy to provide any additional information requested. Thanks for the help.

**Comment by dylansmithing** [comment]
Same for me, neither google contacts or CardDav showing in the contacts window. Also able to provide more info if required.

**Comment by bengotow** [comment]
Hey! This should be fixed in the next release—we finally got approved for read/write access to the Google Contacts API. (It's now a "restricted" scope they only offer to approved apps...)

**Comment by matyhaty** [comment]
@bengotow 

Not fixed for me in 175
Strangely I get the labels come over, but not the contacts

**Comment by fracsi** [comment]
@matyhaty 
Try re-authenticating your Google Account - for me it worked.

**Comment by matyhaty** [comment]
@fracsi 

I went nuclear, uninstalled mailspring, removed mailspring access from google and then re-auth-ed and it worked.

Thanks!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this is /most likely/ resolved in 1.7.6 which shipped this afternoon. 🚀  We made contact sync a bit too aggressive in previous releases and blew through our 1M req / day query limit from Google which was causing a bunch of problems. We also needed to handle Google expiring the "address book version hash" on the server and forcing a re-sync client-side. Finally we also tried to do Contact sync /after/ Calendar sync (which is still in preview mode) and a variety of problems I'm still working on in the calendar engine could cause it to get stuck and not display your contacts. All fixed, so hopefully we're good to go on this one now!

The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!

Will re-open if this problem keeps up :)
