### ISSUE TITLE
Mailspring erasing line-breaks in sent mail

### ISSUE THREAD

**Issue by ItsStevenColling** [Foundry376/Mailspring#1756]
##### Are there any related issues?

I think those two problems may be related or have a similar origin:
- https://github.com/Foundry376/Mailspring/issues/1457
- https://github.com/Foundry376/Mailspring/issues/1183

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

1.7.2-4522b259
If I remember correctly, it was present in previous versions too.

**Bug?**

I often copy text out of Notepad++ into Mailspring when composing mails. In Mailspring's composer it looks fine, but when I send (to myself or checking the mail in the sent-folder), double line-breaks are transformed into single line-breaks. Example:

In Notepadd++ and when copied into Mailspring's composer, it looks like [this](http://stevencolling.com/downloads/misc/github/mailspring_0.png):

> This is a line before the gap.
> 
> This is a line after the gap.

In the received mail (sent/viewed in Mailspring, Thunderbird and Gmail) it turns out like [this](http://stevencolling.com/downloads/misc/github/mailspring_1.png):

> This is a line before the gap.
> This is a line after the gap.

I tried different encodings like UTF-8 or ANSI within Notepad++, if that matters. Single line breaks are not affected. Right now I manually fix these paragraphs in the Mailspring composer by deleting the paragraph and creating a new one. What's weird is, that to delete the paragraph, I have to press the backspace 3 times instead of 2 times: one time to close the gap between the two lines, another one which seems to delete an invisible character and the third one so the second line is moved at the end of the first line and then two times the Enter key to re-create the gap.

Thanks for taking the time!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this should be fixed in the next release, I believe this is the same issue as #1874. If not let me know and I'll take a look!

**Comment by ItsStevenColling** [comment]
Thank you for working on it! I've just installed the new update and the problem persists, sadly. You could reproduce it by yourself by opening Notepad++ (in the case you have it installed), writing something like this:

> This is a line before the gap.
> 
> This is a line after the gap.

...and then copy it over to Mailspring and send it to yourself. You should receive something like this:

> This is a line before the gap.
> This is a line after the gap.

...with the gap respectively double line break missing.

I hope that helps!

**Comment by bengotow** [comment]
Ahh interesting—I was testing by writing the text in Mailspring itself, I wonder if it's different when you paste it in. Will see if I can reproduce this!

**Comment by bengotow** [comment]
Wow I was able to reproduce this in 1.7.6, but only on Windows! Will see what's going on here 👍

**Comment by bengotow** [comment]
Ok round 2! This turned out to be subtle - the problem is that our text editing library SlateJS doesn't handle CRLF delimited plaintext (\r\n newlines instead of just \n), and leaves the \r characters lying around. That means that your "empty" lines really contained one character, the invisible \r. 

Because \r is considered a whitespace character and has no "line height", the lines render with zero height when converted to HTML. The correct solution is to replace these with a `&nbsp;` character which forces the line they're on to have height.

Should be fixed in the next release! Unfortunately I just shipped 1.7.6 today so this missed by a few hours, but stay tuned :)

**Comment by ItsStevenColling** [comment]
Great to hear that you were able to fix this! The invisible \r character also explains why I have to press the return key one more time (to delete the invisible character). Thanks! :)

**Comment by alymoursy** [comment]
This issue is still happening on my mac @bengotow.

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@ItsStevenColling @alymoursy (or anyone else): Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team
