### ISSUE TITLE
Bug: Can't add Office365 account

### ISSUE THREAD

**Issue by toadzky** [Foundry376/Mailspring#1839]
##### What is the behavior you're seeing?
Add account wizard goes blank

##### What email provider (Gmail, Exchange, etc.) are you trying to use?
Office 365

##### What operating system are you using?
Manjaro Linux

##### What version of Mailspring are you using?
1.7.4 via Snap

(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
N/A

I copied the terminal output when it happens:

```
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
```

**Comment by jfk52917** [comment]
Can confirm - I experienced this on Manjaro Linux in both Mailspring 1.7.4 via snap and 1.7.2 built from the AUR.

**Comment by jfk52917** [comment]
I, too, am having this issue. I've tried on 1.7.4 via snap, and 1.7.2 built from the AUR. When adding a second Gmail account, this issue did not occur, leading me to wonder if it only applies to Office365/Exchange accounts.

**Comment by aorozsa** [comment]
I also have this issue. I thought it might've been an issue with my pihole or firewall, but it's not. As @jfk52917 said, no issue with adding a gmail account, but during initial setup, adding an Office365/Outlook account makes the setup window go blank, and with the main window open, it appears normal but doesn't add the accounts.

**Comment by pinkerltm** [comment]
also the same behaviour here

**Comment by sabbakwaas** [comment]
Same issue here.

OS: Ubuntu 19.10
Trying to add Outlook account with 2FA enabled, using app password from Outlook.
Latest Mailspring version from snap

**Comment by drfastolfe** [comment]
Same issue here for Outlook and Office 365 accounts. Can add Gmail.
Seems to be an issue in 1.7.4. Switching back to 1.7.2 fixed the problem.

**Comment by spylacopa** [comment]
Same here with Zimbra account (Outlook/Imap) with version 1.7.4
on both Mac OSX and Opensuse Linux
works in 1.7.2

**Comment by jfk52917** [comment]
Actually, it does appear to work in 1.7.2, downloaded from the AUR - looks like I had put in the wrong password on that version of the application. Downgrading to 1.7.2 may be a solution for those looking.

**Comment by jrmejiaa** [comment]
I have the same problem, I use two different Gmail account (one a corporate one), but if I am using a Office 365 account. The process will say that the account will be added, but it doesn't happen.

**Comment by aorozsa** [comment]
@jfk52917 Is it possible to do this for the snap on Pop!_OS?

**Comment by jfk52917** [comment]
@aorozsa  I've never done this before, so I'm unsure if this would work, but following the StackExchange page available [here](https://unix.stackexchange.com/questions/394421/install-specific-previous-version-of-package-using-snap), it looks like you would type the following command:

```sudo snap install mailspring --channel=1.7.2 --classic```

I'm unsure if you actually need the last flag, so if anyone else knows better, please feel free to comment. If you want to upgrade/downgrade, it appears that you'd add `refresh` in place of `install`. I hope this helps, and sorry for the delay.

**Comment by aorozsa** [comment]
@jfk52917 Nope. Didn't work. This is what it gave me:
```
error: snap "mailspring" is not available on 1.7.2/stable but is available to
       install on the following tracks:

       latest/stable  snap install --stable mailspring

       Please be mindful that different tracks may include different features.
       Get more information with 'snap info mailspring'.
```
Running `snap info mailspring` showed me that **only** 1.7.4 is avaliable, and running `snap install --stable mailspring` just installed 1.7.4.
Thanks for the suggestion anyway.

**Comment by toadzky** [comment]
I was able to install 1.7.2 in manjaro using aur instead of snap

**Comment by aorozsa** [comment]
Mailspring not working doesn't affect me too much; I can always access my accounts via my browser in the meantime. I would, however, like to be using it again asap, so I created a startup script that checks the current version on snap and promts installation if the latest version isn't 1.7.4. I placed the following file into ~/.config/autostart (I use Pop!_OS). Be sure to remove the .txt from the end. I also uninstalled mailspring from my system for the time being.

[install-new-mailspring.desktop.txt](https://github.com/Foundry376/Mailspring/files/4327957/install-new-mailspring.desktop.txt)

**Comment by jgomezdans** [comment]
Just a confirmation that I can reproduce with snap 1.7.4 on Kubuntu 19.10

**Comment by AleksZakirov** [comment]
Hi, I had the same problem, being unable to sign in with my office 365 account. Then I checked the latest version with `snap info mailspring` and saw that an updated edge version 1.7.5 is available. Can confirm that installing this 1.7.5 version allowed me to log in with office 365 no problems. I haven't tested the app any further though.

**Comment by jrmejiaa** [comment]
This bug isn't just with Office 365 account. I have the same issue with an account, which I had added in the past using `IMAP/SMTP` option. I wish you could find the error. I really appreciate the effort.

> I have the same problem, I use two different Gmail account (one a corporate one), but if I am using a Office 365 account. The process will say that the account will be added, but it doesn't happen.

**Comment by jrmejiaa** [comment]
> Hi, I had the same problem, being unable to sign in with my office 365 account. Then I checked the latest version with `snap info mailspring` and saw that an updated edge version 1.7.5 is available. Can confirm that installing this 1.7.5 version allowed me to log in with office 365 no problems. I haven't tested the app any further though.

I can confirm this information in a Linux Mint 18.0 SO. I had problems to work with a Office 365 account and a account, which I had added via `IMAP/SMTP`. Both account now are working using the `mailspring 1.7.5`. If you want to use this version and you are working with `snap` in Linux. You should do the next commands. 

```bash
# First close Mailspring 
sudo snap remove mailspring
sudo snap install mailspring --edge
```

**Comment by jackdnichols** [comment]
jrmejiaa fix worked for me. I'm running OpenSuse Tumbleweed new install as of 04/01/2929

**Comment by jackdnichols** [comment]
I have another account that I would like to add to MailSpring. The account is an Outlook 360 with MFA. How do you add this type of account?

**Comment by jfk52917** [comment]
Creating an app password, and then utilizing that to login to Mailspring,
worked for me. The instructions, published by Microsoft, are available
here:
https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183
.

**Comment by jackdnichols** [comment]
The app passwords option is missing for this account. It is probably locked down.

**Comment by jfk52917** [comment]
Aren't we all these days, my friend. Unfortunately, I'm not entirely sure
how you would proceed, then, as the app passwords method is what I used to
successfully login. My apologies.

**Comment by jackdnichols** [comment]
No worries, I can use the web based version of Outlook for this account.
Thanks.

**Comment by spylacopa** [comment]
can confirm that it works with version 1.7.5 installed via 
sudo snap install mailspring --edge
(openSUSE Tumbleweed)

**Comment by alexandru-calinoiu** [comment]
Beware that installing the app uninstalling and installing the app with --edge will actually delete all your accounts so you have to readd them.

**Comment by smashingx1** [comment]
Pleas fix this bug! :/ My company now uses MFA and just like the first comments says the wizard is blank.

Thank you!!

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - I think it's related to a bug in the current release that causes issues with IMAP account auth. I'm really sorry it's taken so long for the fix in #1876 to get shipped. I will push out a 1.7.5 release tomorrow.

I think we can close it as a dup of #1848 but I'll keep it open until 1.7.5 ships for here for visibility. Thanks everyone for the comments and help triaging!

**Comment by smashingx1** [comment]
@bengotow thank you, Do you guys have any IRC channel where we can ask questions in real time by any chance?

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀 The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!

@smashingx1 — there's a Mailspring Slack over here! https://join-mailspring-slack.herokuapp.com/ It's mostly for users to chat about themes etc but I'm in there a fair bit as well :)

**Comment by OmarMorando** [comment]
Hi, I've the same problem with 1.7.8 on Kubuntu 20.04

**Comment by NIKKE1** [comment]
Problem persists in: 1.8.0-8983dca2

Sorry we had trouble logging you in
"ErrorNamespace (IMAP)"

If i try to add imap servers manually I get authentication error.

**Comment by CodeMouse92** [comment]
@OmarMorando @NIKKE1 Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
