### ISSUE TITLE
Bug: White Screen after configure new version 1.7.4

### ISSUE THREAD

**Issue by sammish** [Foundry376/Mailspring#1841]
White Screen Issue after configure mainspring 1.7.4 
![Peek 2020-03-04 09-09](https://user-images.githubusercontent.com/12432802/75850339-1ee7c600-5df8-11ea-806a-2ef3ba2b1c58.gif)

**Comment by Tayeh** [comment]
same issue with me in fedora 31

**Comment by sammish** [comment]
I fixed this issue with old version https://github.com/Foundry376/Mailspring/releases/tag/1.7.2

**Comment by NIKKE1** [comment]
same issue with me in Ubuntu 19.10

**Comment by jacobSND** [comment]
Same issue on Ubuntu 18.04, 1.7.2 works

**Comment by benjamintomad** [comment]
Same issue on Elementary 5.1.2, 1.7.2 works

**Comment by pskopnik** [comment]
#112

**Comment by daniellobrunello** [comment]
Same Issue on macOS 10.14.6

**Comment by ravenstar68** [comment]
I'm seeing the same thing with Linux Mint.
I ran mailspring from the terminal to see if any error messages were forthcoming and got this:

{"error":null}
```
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
```

**Comment by samtuke** [comment]
Same issue here on Fedora 31 desktop (Gnome) using RPM-based installation

**Comment by ravenstar68** [comment]
I wanted to clarify.  This problem specifically occurs when adding a IMAP/POP3 account.  I have managed to successfully add a Gmail account.

**Comment by schapira** [comment]
same for me woth disroot.org mail at windows 10

**Comment by thebodzio** [comment]
Another confirmation: Windows 10, home.pl IMAP account

**Comment by ArbeidW** [comment]
Same for me for Office 365

**Comment by gravcat** [comment]
Downgrading to 1.7.1 fixed it for me. Not that 1.7.2 or 1.7.3 wouldn't have, it just happened to work with this one as the first I picked.

https://github.com/Foundry376/Mailspring/releases

**Comment by samtuke** [comment]
Some reassurance from @bengotow that the core team is aware of and working on this issue would be appreciated.

**Comment by wreedheid** [comment]
> 
> 
> Some reassurance from @bengotow that the core team is aware of and working on this issue would be appreciated.

Same issue here, however: I got a reply from Ben that an update will come this month with bug fixes.

**Comment by kaulex99** [comment]
> 
> 
> > Some reassurance from @bengotow that the core team is aware of and working on this issue would be appreciated.
> 
> Same issue here, however: I got a reply from Ben that an update will come this month with bug fixes.

Same issue!
Hope soon, otherwise I have to switch to another client :(

**Comment by YurySolovyov** [comment]
> Hope soon, otherwise I have to switch to another client :(

Dude, just use 1.7.2

**Comment by wreedheid** [comment]
> 
> 
> > Hope soon, otherwise I have to switch to another client :(
> 
> Dude, just use 1.7.2

@kaulex99 What @YurySolovyov says is true, use 1.7.2 configure everything, then let it update to the latest version. Everything works and you can wait for the 1.7.5 with some minor inconveniences. No need to (spread) panic and talk about 'switching clients' imho.

**Comment by fahimipour** [comment]
same issue on Arch linux, had to downgrade for now.

**Comment by isneezy** [comment]
I got the same bug on elementaryOS, and I've installed via snap. Unfortunately there is no way to install previous versions of mailspring via snap.

**Comment by usfbrian** [comment]
Installed via .deb on 20.04, can add Gmail via OAuth but not IMAP---same white screen as everyone.

```
Running database migrations
App load time: 225ms

Running Setup
{"error":null}
Manual update check (updates.getmailspring.com/check/linux/x64/1.7.4-d54ff730/anonymous/stable) returned 204
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }

```

**Comment by bblaha** [comment]
Another confirmation. Also installed via snap on Ubuntu 20.04 Beta, white screen.
Had the same problem before on 19.10 as well, but now it is installed via snap and I still have to look into downgrading that :/

**Comment by ravenstar68** [comment]
To those saying roll back to 1.7.2  That's fine for those that are comfortable manually installing the RPM, but if you are using something like Snap, then that option is not available to you.  I alsow have the Windows version and that automatically updated to 1.7.4 as well.  I tried updating the IMAP server and was greeted with the same white screen.

This has now been going on a month.  Best practice would have been to roll back the update or address the issue.  Wih bblaha's comment that 1.7.5 is showing the same issue, then that is increasingly looking like the best course of action.

After all it's a critical issue if new users can't add IMAP or POP3 accounts and are only limited to accounts such as Outlook.com and Gmail which use OAUTH2.

**Comment by martin-nitram** [comment]
exactly

**Comment by bblaha** [comment]
> Another confirmation. Also installed via snap on Ubuntu 20.04 Beta, white screen.
> Had the same problem before on 19.10 as well and downgraded to 1.7.2, but now it is installed via snap and I still have to look into downgrading that :/
> Adding to that: The same problem appears on the latest/edge channel with 1.7.5, so no solution in sight apparently

I have to correct my last sentence: Now after a restart it does seem to work with 1.7.5 on the latest/edge channel. So for all of you snap users (or Ubuntu 20.04 users), setting the snap channel to latest/edge should fix that. Sorry if this caused confusion!

**Comment by isneezy** [comment]
> I have to correct my last sentence: Now after a restart it does seem to work with 1.7.5 on the latest/edge channel.

Unfortunately this doesn't work for me.

**Comment by heitorfreitasferreira** [comment]
Same on Ubuntu 19.10
![image](https://user-images.githubusercontent.com/47534514/79084336-9408be00-7d09-11ea-90d9-81f043ddfbef.png)

**Comment by ravenstar68** [comment]
Update
Half fixed in 1.7.5
We can now add IMAP/POP3 accounts and view the mail - BUT if you try to go into the Connection settings dialog we now have annother white screen.

Again this worked on 1.7.2

Tim

**Comment by sammish** [comment]
Thanks for the ne version release. Problem has been resolved.

**Comment by VuiMuich** [comment]
In Windows 10 (Build 19041.207) with Mailspring 1.7.5 this still persists.

**Comment by sammish** [comment]
@VuiMuich It's okay me. I have Zorin OS

Please   try complete reinstall.

**Comment by VuiMuich** [comment]
right now I hav booted my Manjaro Install, where I did a fresh install with 1.7.4 (via AUR) and updated just an hour later.
Is there a way to completely reinstall without having to set up all accounts again?

**Comment by sammish** [comment]
@VuiMuich 
Then, Please stick on with older version 1.7.2

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved in a later release, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our Discourse.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. Learn more about the changes here.

We hope to see you there soon!

-The Mailspring Team
