### ISSUE TITLE
Bug: New lines in text/plain email

### ISSUE THREAD

**Issue by Kladizkov** [Foundry376/Mailspring#1853]
**Describe the bug**
After the Feb 25, 2020 update ( to version 1.7.4 ), I started to notice that the contents of some emails are appearing in a single line without the new line breaks. These were all text/plain emails. 

**To Reproduce**
Send a text/plan email with multiple new lines to your address configured in mailspring. When the mail is received, open and view the email.

**Expected behavior**
The line breaks in the original text/plain email should show as is in the mailspring email view.

**Setup: (please complete the following information):**
 - OS: Linux Mint
 - OS Version 19
 - Mailspring Version: 1.7.4

**Comment by sarajcev** [comment]
I've noticed this as well! 
Ubuntu 18.04
Mailspring Version 1.7.4

**Comment by rsalevsky** [comment]
I can confirm as well that after the update to 1.7.4 new lines are not shown as expected.

**Comment by paulocoghi** [comment]
Not only that. When I try to compose a new email, it is always set in plain text mode, even when the configuration is set to rich text.

**Comment by chipbuster** [comment]
Present on Windows 10, 1.7.4.

> When an email arrives that contains ONLY a plaintext MIME part, Mailspring now displays it in the app in plain text with display:pre formatting so newlines are preserved. I think this will make the mailing list reading experience much better.

Noticed this in the comment announcing plaintext support. Is there a chance that this is responsible/a way to temporarily disable this feature?

**Comment by ondrej-petr** [comment]
I have the same problem on Windows 10, ver. 1.7.4

**Comment by paulocoghi** [comment]
> Also, when I try to compose a new email, sometimes it goes in plain text mode (which also removes the signature), even when the configuration is set to rich text.
> 
> Only closing and reopening Mailspring solve this.

This particular issue was [solved](https://github.com/Foundry376/Mailspring/issues/1894) on 1.7.5! :tada: :tada: :tada: :tada: :tada:

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this, we fixed a bug in 1.7.5 that caused the app to author all new drafts in plaintext mode (ironically it got confused and thought you were holding the Alt key indefinitely...) This sounds like it may be a bit different though—let me take a look today and I'll keep you posted.

**Comment by Kladizkov** [comment]
I upgraded to 1.7.5, but I still have the new line issues. My problem is not during the composing stage. It is the mails that I receive that doesn't have new lines appearing in it. It all comes in one single line.

**Comment by paulocoghi** [comment]
It is a diferent issue, @Kladizkov . @bengotow is working on this. But I confirm that the fixes brought in 1.7.5 were excellent.

**Comment by bengotow** [comment]
Hey! I believe the problem with new lines should be fixed in the next release. I hadn't realized that you were referring (I think) to the whitespace in the reply text? I was able to reproduce a problem where this text outlined in red below would all be on one line if you were replying in rich text and the incoming email was in plain text.

Will ship this fix in the next release!

![image](https://user-images.githubusercontent.com/1037212/80300213-56238500-8760-11ea-9f38-18fd536f649a.png)

**Comment by ondrej-petr** [comment]
Hi Ben,
i beleive that the bug was refering to entire incoming message (at least in my case).

Regards
Ondřej

**Comment by rsalevsky** [comment]
Hi Ben, here is an example of an single line incoming message:

![singleline](https://user-images.githubusercontent.com/4128547/80370123-b8c76e80-888f-11ea-8942-07334a081ac9.png)

**Comment by Kladizkov** [comment]
I think this is something about the charset when its missing in the email headers.

Try sending an email with this email headers.

```
From: someone@someone.com
Subject: MyEmail
To: someone@someone.com
Date: Tue, 28 Apr 2020 10:14:29 +0530 (IST)
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="bound1588023280"

This is a multi-part message in MIME format.

--bound1588023280
Content-type: text/plain

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,


Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,

--bound1588023280--
```

It will appear like this

![Screenshot from 2020-04-28 11-04-05](https://user-images.githubusercontent.com/24489785/80451159-c1c44880-8940-11ea-9f4f-eba7d8ad4ce4.png)

**Comment by Kladizkov** [comment]
After upgrading to 1.7.8, I see this issue fixed.

**Comment by paulocoghi** [comment]
I also confirm this issue is solved on 1.7.8

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
