### ISSUE TITLE
Error when trying to download attachment

### ISSUE THREAD

**Issue by nickolasclarke** [Foundry376/Mailspring#189]
##### Are there any related issues?

not that I can find

##### What operating system are you using?
Win 10

##### What version of Mailspring are you using?
1.0.5

--

**Bug?**
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly Zoho

##### Is the issue reproducible with a particular attachment, message, signature, etc?

An email with a PDF attached cannot be found when trying to download. I get the following error message. I suspect it may have to do with non-latin chars being in the filename? Unclear. I cant find any errors in the logs. 

![snip_20171017122607](https://user-images.githubusercontent.com/2177320/31676507-6cae3ab4-b39a-11e7-996a-28966dfdd9ea.png)
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this — i think this is definitely a problem with the file paths - these characters might not be valid on your filesystem. I'll see if I can reproduce this here and get back to you.

**Comment by nickolasclarke** [comment]
@bengotow let me know if you need anything from me to help recreate the problem.

**Comment by abelmathew** [comment]
Throwing my hat into the ring: I am experiencing this problem as well. Screenshot attached: 

![image](https://user-images.githubusercontent.com/1058729/32460708-99529a44-c301-11e7-8529-f0b78d7064ee.png)

**Comment by d-makarenko** [comment]
Same for me. It fails to download attachment, or even show it in the message if its name contains Cyrillic characters. 
OS: Windows 7 x64.

![default](https://user-images.githubusercontent.com/31288426/32542635-4aee7e98-c484-11e7-9a3e-4b71958dcb25.png)

**Comment by d-makarenko** [comment]
It works fine on linux, though.

**Comment by bengotow** [comment]
Hey folks! Yep this one is windows-specific and was fixed in 1.0.7 - if you
go the apps menu in the top right of the window and choose “Check for
Updates”, it should download and install the fixed version. It only impacts
new email that arrives unless you go into Preferences > General and click
“reset email cache” at the very bottom.

**Comment by d-makarenko** [comment]
Great! Thank you!

**Comment by d-makarenko** [comment]
Is it fixed in 1.0.7-664204d8? This is the latest version available on getmailspring.com. I can't use built-in updater because of our internet access is restricted by proxy server.

**Comment by bengotow** [comment]
Hey! So sorry–I was wrong. I fixed this on the same day I shipped 1.0.7, but it wasn't included. Just shipped 1.0.8 this morning, thankfully—it should be working now.

Here's a direct link to the new version: https://mailspring-builds.s3.amazonaws.com/client/5a837d0e/win-ia32/MailspringSetup.exe

**Comment by hawajskiwilkolak** [comment]
Problem still occurs in version 1.2.1

Visible on screen path "C:\Users\MichałGrzelak\AppData\Roaming\Mailspring\files" is valid and works normally on Windows, but directory is empty.

![image](https://user-images.githubusercontent.com/8860242/38307531-4d726fa4-3814-11e8-8f26-42e6af1d6d88.png)

Problem occurs for all attachments.

**Comment by eNeLGe** [comment]
"Rebuild Cache" solved the issue for me.  Preferences>Accounts>Account Settings>Rebuild Cache

**Comment by korenyako** [comment]
I have the same problem with all attachments. Version 1.2.2 Directory is empty.

![image](https://user-images.githubusercontent.com/22962316/41769458-ff8d1d2e-7617-11e8-9ab4-7e2dcdf47c3c.png)
