### ISSUE TITLE
Mails persist in the trash after emptying the trash

### ISSUE THREAD

**Issue by rafrsr** [Foundry376/Mailspring#220]
##### Are there any related issues?
no

##### What operating system are you using?
17.10

##### What version of Mailspring are you using?
1.0.5

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![image](https://user-images.githubusercontent.com/7094012/31831554-e54ed0d4-b591-11e7-80f1-e179b7d3b5f4.png)

the first message in the list I do not understand what it does there, it is the last sent message, i never delete it.

If others emails are moved to trash and click "Empty Trash..." all mails are cleared except this two emails in the list.

**Comment by bengotow** [comment]
Hey! This is super interesting - Mailspring is showing this thread as having the "trash" folder even though it's messages are no longer in the trash. I'll see if I can reproduce this. In the meantime, a sure-fire way to fix this would be to drag it out of the trash (and then back in to the trash if you actually want it to be there.)

**Comment by palefire19** [comment]
Yeah, I've got something similar. An email thread simultaneously is showing up in my Inbox (duplicated - see my other communication on this Ben in #173 ) and then also in the trash. When I click on it in the trash I get the same message as @rafrsr ("There are x more messages in this thread that are not in spam or trash").

**Comment by agurz** [comment]
Something similar here ✋, running Mailspring 1.0.7. 

Clue: The problematic thread is detected as unread when is taken to count unread messages for sidebar labels but it's being shown as read on the mail list:

<img width="856" alt="screen shot 2017-11-01 at 11 31 23 am" src="https://user-images.githubusercontent.com/13837769/32279684-3c2c763a-bef8-11e7-8bb6-07ff20416e13.png">

**Comment by dardin88** [comment]
I have the same issue, running Mailspring 1.0.7.

I am using Gmail and this is particularly awkward since the mails are actually deleted (e.g., I cannot find them on Gmail), but they persist on Mailspring.

**Comment by bengotow** [comment]
Hey folks—this should be fixed in the next release. Stay tuned 👍

**Comment by hheld** [comment]
This is not fixed for me even with the latest version. I see a message in the trash that I had opened at some point (which was an old message in my sent folder). After that, I see the exact same old message in the trash but with a bogus date of Jan. 1 1970. In GMail, this message does not exists, and I cannot delete it from Mailspring at all. Moving that to a different folder does nothing except that I see the non-existing message in the different folder in Mailspring ...

**Comment by utklasad** [comment]
@hheld exactly the same problem here!

**Comment by ArchAngelIT** [comment]
Can confirm normal operation on the current version and stuck emails deleted.

Steps taken, manually deleting the edgehill.db file at %USERNAME%\AppData\Roaming\Mailspring\ while having made sure all mailspring processes were stopped and then restarted after.

while the option of clearing file is present on the general settings menu (button at the bottom) I found it did not remove the .db file because a process was hanging for some reason.

**Comment by Melissa-Kay** [comment]
I have the same issue. Emails randomly show up in my trash that I never put there. At first I thought it was caused by archiving (and it still might be) but I don't recall ever archiving 2 of the threads that appeared there today.

Here's a side by side comparison of mailspring trash vs gmail. 

<img width="1732" alt="screen shot 2018-08-16 at 5 49 09 pm" src="https://user-images.githubusercontent.com/3027874/44236949-bb963480-a17c-11e8-8afa-a1cd183ea917.png">

Notice the two started emails doesn't show up in gmail. Those are active threads I have in my inbox.

**Comment by LogX7** [comment]
SAME ISSUE HERE

**Comment by jijojosephk** [comment]
I'm also facing the same issue. Having version "1.6.0-10f5c95c" on Ubuntu 18.04 LTS. Even after clicking on empty trash, some conversations are still there. I doubt this happens when we start writing a reply to someone and then delete the message/draft.

**Comment by unseeingdog** [comment]
I'm also having this issue. I can confirm that in my case it happens specifically when I start a reply and then delete the draft. It happens every single time. The only way to clear the messages seems to be hitting "Rebuild cache" for the account in question.

**Comment by dfrechdev** [comment]
I have the same issue with version 1.6.3-134a0e55.

**Comment by stevedude** [comment]
Same issue here. I was able to get rid if a couple emails in the trash bin by finding the original thread whether it was in the Sent folder or elsewhere, delete that, then run "Empty Trash Now".

My trash folder is getting larger and slowly other emails are being added. It would be nice to get a resolution soon.
![Trash](https://user-images.githubusercontent.com/8483863/66792449-b76fbf00-eec6-11e9-9208-52c2fc283220.png)

**Comment by FernandoGarcia** [comment]
Hi @bengotow ! 
This problem persists in 1.7.2.

**Comment by artsgirl** [comment]
I also am having this problem. As others have mentioned, the issue arises when I start and then delete a draft. These messages then stay in trash forever, even on a reinstall (even after a total wipe of Windows, in fact). So the cache of messages like this in my trash folder is getting larger and larger, making it harder and harder to see what is legitimately supposed to be in the trash folder and make sure nothing is getting deleted by mistake.

This issue has been going on for over two years according to this thread. I am a paid supporter of MailSpring. Do the devs still work on this? I'm not sure what my money is going to, honestly. I submitted a support ticket on a separate issue through the website a couple weeks ago and never got a response of any kind.

**Comment by Vicente-M** [comment]
Hi, the only and radical way to empty the bin was this

![Captura de pantalla (111)](https://user-images.githubusercontent.com/23098747/69893871-f68f8d80-1317-11ea-9aa8-0f1c6aa46d95.png)

**Comment by b4mboo** [comment]
Caching is hard. Hitting the "Reset Cache" button was the only thing that helped. Thanks! :sparkles:

**Comment by MaxHausmann** [comment]
Thank you. Reset caching saved my life! Using three accounts and some messages appeared again and again for one year or longer. Today I had enough time to clean all the folders from the servers directly. But the problem remained - so I used the final solution: "reset cache" -> works! And my mails are now sorted, too.

**Comment by Babsky** [comment]
More than 3 years on and this is still an issue!
Version 1.7.8- 13635bcf
Clearing out inbox so filter (by sender/in:inbox), select multiple (select 1st, hold down Shift, select last - seems the only way to select multiple emails), click the bin icon at the top.
Emails still there, still selected (even though filtered on inbox).
Go to "Trash", click "Empty trash now", all emails still there.
Reset Cache, trash now empty.
It's not great as this has been a problem for so long.
"done-pending-release on 8 Nov 2017", well if it was fixed someone broke it again!

**Comment by christophlandon** [comment]
I'm running the latest build 180 and facing the same issue as some of you here with "There are X more messages in this thread that are not in spam or trash". I wish someone would finally fix this bug.

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@christophlandon: Can you please open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team
