### ISSUE TITLE
Issue syncing my IMAP mailbox

### ISSUE THREAD

**Issue by domenico-ruggiano** [Foundry376/Mailspring#230]
My IMAP account **correctly** configured based on the provider has this settings:

##### IMAP
- **Server**: imaps.aruba.it
- **Port**: 993
- **Security**: SSL/TSL
- My user & pass

##### SMTP
- **Server**: smtps.aruba.it
- **Port**: 465
- **Security**: SSL/TSL
- My user & pass

The issue is reproducible in many ways, one that always throws the problem is:
1. Start Mailspring (IMAP account has been already configured correctly)
2. The box in the bottom-left corner "Syncing with your mailbox..." displays and after a while the mail is correctly syncronized.
3. With another account (outlook account) I'll send to the imap account an email throw another web client and test if the mail is received
4. In Mailspring, top-right corner, click on the button **"Sync New Mail Now"**
5. Just after the click, close Mailspring during the sync and Mailspring will be reduced in the Traybar in Windows 10 but still working.
6. If I open Mailspring, not only the sync has not been done, but Mailspring will never sync my account again. Pushing "Sync New Mail Now" will produce no results.
7. I need to **quit** Mailspring through the traybar in Windows and open it again to get the mail synced and Mailspring working again.

This problem is reproducible in many other ways, that I'm not able to describe the procedure like I've done for this one, right now. But, at the end, **my IMAP account will not be synced anymore until I quit Mailspring and open it again.**

Hope this helps.

**More**: _I tryed to reset my configuration and also to reset my account many times. This issue always persists._

##### Are there any related issues?

Don't think so

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.0.6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

**Comment by bengotow** [comment]
Hey! Can you attach the mailsync logs in `C:\Users\<your username>\Roaming\Mailspring\mailsync-***.log`? It sounds like the app can't find a folder to "idle" on in your account, so you'll only see new mail every 60 seconds or 120 seconds when it checks.

**Comment by domenico-ruggiano** [comment]
Sure:
```log
12552 [2017-10-23 21:44:15.311] [background] [info] syncFolderChangesViaCondstore - INBOX.[Mailspring].Snoozed: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:44:15.312] [background] [info] Sync loop deleting unlinked messages with phase 1.
12552 [2017-10-23 21:44:15.313] [background] [info] Sync loop complete.
12552 [2017-10-23 21:45:02.884] [main] [info] Marking all folders as `busy`
12552 [2017-10-23 21:45:02.885] [background] [info] Syncing folder list...
12552 [2017-10-23 21:45:03.039] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:45:03.097] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:45:03.145] [background] [info] syncFolderChangesViaCondstore - INBOX.Drafts: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:45:03.196] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:45:03.243] [background] [info] syncFolderChangesViaCondstore - INBOX.SPAM: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:45:03.291] [background] [info] syncFolderChangesViaCondstore - INBOX.Templates: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:45:03.339] [background] [info] syncFolderChangesViaCondstore - INBOX.[Mailspring].Snoozed: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:45:03.341] [background] [info] Sync loop deleting unlinked messages with phase 2.
12552 [2017-10-23 21:45:03.341] [background] [info] Sync loop complete.
12552 [2017-10-23 21:45:31.749] [metadata] [info] Metadata delta stream closed.
12552 [2017-10-23 21:45:31.750] [metadata] [info] Metadata delta stream starting...
12552 [2017-10-23 21:46:03.004] [main] [info] Marking all folders as `busy`
12552 [2017-10-23 21:46:03.005] [background] [info] Syncing folder list...
12552 [2017-10-23 21:46:03.145] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:03.287] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:03.336] [background] [info] syncFolderChangesViaCondstore - INBOX.Drafts: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:03.382] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:03.955] [background] [info] syncFolderChangesViaCondstore - INBOX.SPAM: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:04.002] [background] [info] syncFolderChangesViaCondstore - INBOX.Templates: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:04.052] [background] [info] syncFolderChangesViaCondstore - INBOX.[Mailspring].Snoozed: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:04.054] [background] [info] Sync loop deleting unlinked messages with phase 1.
12552 [2017-10-23 21:46:04.054] [background] [info] Sync loop complete.
12552 [2017-10-23 21:46:05.468] [foreground] [info] Idle exited with code 0
12552 [2017-10-23 21:46:05.469] [foreground] [info] Idling on folder INBOX
12552 [2017-10-23 21:46:13.724] [main] [info] Marking all folders as `busy`
12552 [2017-10-23 21:46:13.725] [background] [info] Syncing folder list...
12552 [2017-10-23 21:46:13.863] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:13.911] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:13.960] [background] [info] syncFolderChangesViaCondstore - INBOX.Drafts: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:14.007] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:14.057] [background] [info] syncFolderChangesViaCondstore - INBOX.SPAM: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:14.109] [background] [info] syncFolderChangesViaCondstore - INBOX.Templates: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:14.155] [background] [info] syncFolderChangesViaCondstore - INBOX.[Mailspring].Snoozed: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:46:14.157] [background] [info] Sync loop deleting unlinked messages with phase 2.
12552 [2017-10-23 21:46:14.158] [background] [info] Sync loop complete.
12552 [2017-10-23 21:47:27.774] [main] [info] Marking all folders as `busy`
12552 [2017-10-23 21:47:27.775] [background] [info] Syncing folder list...
12552 [2017-10-23 21:47:27.924] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:47:27.976] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:47:28.023] [background] [info] syncFolderChangesViaCondstore - INBOX.Drafts: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:47:28.069] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:47:28.115] [background] [info] syncFolderChangesViaCondstore - INBOX.SPAM: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:47:28.164] [background] [info] syncFolderChangesViaCondstore - INBOX.Templates: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:47:28.245] [background] [info] syncFolderChangesViaCondstore - INBOX.[Mailspring].Snoozed: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:47:28.245] [background] [info] Sync loop deleting unlinked messages with phase 1.
12552 [2017-10-23 21:47:28.246] [background] [info] Sync loop complete.
```

I tried to sync a couple of times, then at **21:46** I sent to my IMAP account an email with my outlook account. Each sync after 21:46 should have returned the new message, but the new message has not been displayed.

After that, I went in menu -> developer -> reload at **21:50**.
Mailstamp reloads, and finally display correctly the new message. This is the "new" log after 21:47:

```log
12552 [2017-10-23 21:48:04.677] [foreground] [info] Idle exited with code 0
12552 [2017-10-23 21:48:04.678] [foreground] [info] Idling on folder INBOX
12552 [2017-10-23 21:49:28.248] [background] [info] Syncing folder list...
12552 [2017-10-23 21:49:28.388] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:49:28.437] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:49:28.485] [background] [info] syncFolderChangesViaCondstore - INBOX.Drafts: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:49:28.532] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:49:28.578] [background] [info] syncFolderChangesViaCondstore - INBOX.SPAM: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:49:28.624] [background] [info] syncFolderChangesViaCondstore - INBOX.Templates: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:49:28.673] [background] [info] syncFolderChangesViaCondstore - INBOX.[Mailspring].Snoozed: highestmodseq, uidnext match, no changes.
12552 [2017-10-23 21:49:28.674] [background] [info] Sync loop deleting unlinked messages with phase 2.
12552 [2017-10-23 21:49:28.675] [background] [info] Sync loop complete.
12552 [2017-10-23 21:50:04.794] [foreground] [info] Idle exited with code 0
12552 [2017-10-23 21:50:04.794] [foreground] [info] Idling on folder INBOX
14568 [2017-10-23 21:50:50.069] [main] [info] ------------- Starting Sync (domenico.ruggiano@crmpartners.it) ---------------
14568 [2017-10-23 21:50:50.078] [background] [info] Marking all folders as `busy`
14568 [2017-10-23 21:50:50.078] [metadata] [info] Metadata delta stream starting...
14568 [2017-10-23 21:50:50.080] [background] [info] Syncing folder list...
14568 [2017-10-23 21:50:51.012] [background] [info] Syncing folder list...
14568 [2017-10-23 21:50:51.152] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq changed, requesting changes...
14568 [2017-10-23 21:50:51.447] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:51.497] [background] [info] syncFolderChangesViaCondstore - INBOX.Drafts: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:51.542] [foreground] [info] Idling on folder INBOX
14568 [2017-10-23 21:50:51.542] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:51.620] [background] [info] syncFolderChangesViaCondstore - INBOX.SPAM: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:51.665] [background] [info] syncFolderChangesViaCondstore - INBOX.Templates: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:51.700] [background] [info] syncFolderChangesViaCondstore - INBOX.[Mailspring].Snoozed: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:51.700] [background] [info] Sync loop deleting unlinked messages with phase 2.
14568 [2017-10-23 21:50:51.700] [background] [info] Sync loop complete.
14568 [2017-10-23 21:50:51.701] [background] [info] Syncing folder list...
14568 [2017-10-23 21:50:51.846] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:51.905] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:51.951] [background] [info] syncFolderChangesViaCondstore - INBOX.Drafts: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:52.006] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:52.058] [background] [info] syncFolderChangesViaCondstore - INBOX.SPAM: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:52.107] [background] [info] syncFolderChangesViaCondstore - INBOX.Templates: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:52.153] [background] [info] syncFolderChangesViaCondstore - INBOX.[Mailspring].Snoozed: highestmodseq, uidnext match, no changes.
14568 [2017-10-23 21:50:52.153] [background] [info] Sync loop deleting unlinked messages with phase 1.
14568 [2017-10-23 21:50:52.153] [background] [info] Sync loop complete.
14568 [2017-10-23 21:51:05.092] [metadataExpiration] [info] Scanning for expired metadata
14568 [2017-10-23 21:51:05.092] [metadataExpiration] [info] -- Will wake for next expiration in 7201sec
```

**Comment by domenico-ruggiano** [comment]
Any news on this? 
Do you need some more information?
I can help 😄

**Comment by lxalln** [comment]
I'm also having trouble syncing with an IMAP account (powered by ZOHO).

This is the error:
`[error] syncFolderUIDRange - Fetching full headers for 1`

This looks to be a new error message since 1.0.7.

If this is a different issue, I'm happy to open a new issue, and provide whatever information I can.
New emails can be received, but because the account is in a 'broken' state, I can't delete, mark as read or send new emails.

**Comment by lxalln** [comment]
@bengotow I am getting this same problem in Windows & Linux, but in Linux I'm seeing a more detailed error message:

```
21111 [2017-11-04 09:57:36.060] [foreground] [info] Idling on folder INBOX
21111 [2017-11-04 09:57:36.444] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** too many SQL variables
 ***
```

Hope that helps narrow this issue down.

**Comment by lxalln** [comment]
@bengotow 1.0.8 appears to have resolved this issue for me.

**Comment by bengotow** [comment]
Hey folks, this should be fixed in the next release. It turns out there was a combination of IMAP extensions that we didn't support. If your provider supported both `QRESYNC` and `CONDSTORE`, Mailspring wouldn't recognize new mail for a very long time if it was running idle.

**Comment by domenico-ruggiano** [comment]
@bengotow thank you very much! I'm currently still having this issue, so I'm really excited to test it on the next new pending release and I'll let u know 😄 

Thank you so much again!

**Comment by bengotow** [comment]
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Gonna go ahead and close this—if you continue to have trouble after the update, let me know and I'll re-open it!
