### ISSUE TITLE
Inbox showing count when no emails are within the inbox.

### ISSUE THREAD

**Issue by cepitspace** [Foundry376/Mailspring#29]
##### Are there any related issues?
Not that I'm aware of.

##### What operating system are you using?
Windows 10.

##### What version of Mailspring are you using?
1.0.1-ba1d6734

**Bug?**
Inbox count is shown when no emails are located within the inbox.

##### Do you have any third-party plugins installed? If so, which ones?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I'm using Gmail, haven't tested other providers.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I believe it's just that I have unread emails that are in the trash.
![mailspring_2017-10-04_23-38-42](https://user-images.githubusercontent.com/31072838/31203051-3e0ce2a6-a95d-11e7-87c1-0fa1a94a7d68.png)

--

**Comment by agurz** [comment]
I think this is also happening when emails are read in another client. It seems that Mailspring realizes that emails were read but it doesn't update the unread count on the sidebar

**Comment by bengotow** [comment]
Hey folks! This should be fixed in the next release (Mailspring does a better job "balancing" the counters.) Cheers—

**Comment by lxalln** [comment]
@bengotow this issue is still present in 1.0.8.

The issue is with emails that are in the 'bin' still being tagged as 'Inbox' according to MailSpring.

No unread emails, but still have indicator:
![image](https://user-images.githubusercontent.com/2781908/32737696-aa7db5c4-c892-11e7-88bd-f8e95a797b31.png)

Showing a deleted email that is apparently still in the inbox. Marking this manually as read, removes the indicator against the inbox.

![image](https://user-images.githubusercontent.com/2781908/32737831-0f2d2c7a-c893-11e7-97b7-02eb333171b7.png)
