### ISSUE TITLE
Emails Disappear From Inbox

### ISSUE THREAD

**Issue by jGleitz** [Foundry376/Mailspring#304]
After setting up Mailspring, everything is working perfectly for some time (10 minutes or so). After that, mails disappear from the Inbox. That means that they are still in the Inbox on the server and are correctly shown by other clients, but not displayed by Mailspring. Curiously, not all emails disappear (but most do). No newly received emails are shown.

There are no errors indicated in the UI. The Developer console shows a lot of exceptions like the one below, but I think they are not related:

```
/usr/share/mailspring/resources/app.asar/src/error-logger.js:114 Error: onChildScrollRequest: expected id or rect
```
<details>
<summary>Stack Trace</summary>

```
    at Object.MessageList._scrollTo [as scrollTo] (/internal_packages/message-list/lib/message-list.jsx:360:13)
    at ComposerEditor._scrollToBottom (/internal_packages/composer/lib/composer-editor.jsx:189:30)
    at Object.ComposerEditor._ensureSelectionVisible [as onSelectionRestored] (/internal_packages/composer/lib/composer-editor.jsx:239:12)
    at Contenteditable._notifyOfSelectionRestoration (/src/components/contenteditable/contenteditable.cjsx:567:14)
    at Contenteditable._notifyOfSelectionRestoration (/src/components/contenteditable/contenteditable.cjsx:1:1)
    at Contenteditable.componentDidUpdate (/src/components/contenteditable/contenteditable.cjsx:154:8)
    at Contenteditable.componentDidUpdate (/src/components/contenteditable/contenteditable.cjsx:1:1)
    at CallbackQueue.notifyAll (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/CallbackQueue.js:76:22)
    at ReactReconcileTransaction.close (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconcileTransaction.js:80:26)
    at ReactReconcileTransaction.closeAll (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:209:25)
    at ReactReconcileTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:156:16)
    at ReactUpdatesFlushTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:143:20)
    at ReactUpdatesFlushTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:89:32)
    at Object.flushBatchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:209:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:156:16)
    at Object.batchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.enqueueUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:200:22)
    at enqueueUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:24:16)
    at Object.enqueueSetState (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:218:5)
    at _class.ReactComponent.setState (/usr/share/mailspring/resources/app.asar/node_modules/react/lib/ReactBaseClasses.js:64:16)
    at DraftEditingSession._sessionUnlisten.session.listen (/src/decorators/inflates-draft-client-id.jsx:63:16)
    at EventEmitter.eventHandler (/src/flux/modules/reflux-coffee.coffee:117:18)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at DraftEditingSession.trigger (/src/flux/modules/reflux-coffee.coffee:125:17)
    at Object.DraftEditingSession.changeSetDidAddChanges [as onDidAddChanges] (/src/flux/stores/draft-editing-session.es6:453:10)
    at DraftChangeSet.add (/src/flux/stores/draft-editing-session.es6:60:20)
    at Object.ComposerView._onBodyChanged.event [as onChange] (/internal_packages/composer/lib/composer-view.jsx:550:32)
    at Contenteditable._onDOMMutated (/src/components/contenteditable/contenteditable.cjsx:342:14)
    at MutationObserver.<anonymous> (/src/components/contenteditable/contenteditable.cjsx:1:1) 
```
</details>

<p></p>

The log shows no direct errors, but some things seem odd. This seems to be the sequence where Mailspring decides to delete the emails from its copy of the inbox¹:

<details>
<summary> Log excerpt</summary>

```
14891 [2017-11-04 16:01:08.500] [background] [info] Sync loop complete.
14891 [2017-11-04 16:01:08.501] [background] [info] Syncing folder list...
14891 [2017-11-04 16:01:08.588] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq changed, requesting changes...
14891 [2017-11-04 16:01:08.642] [background] [info] - Building queries for range 1-8563
14891 [2017-11-04 16:01:08.642] [background] [info] - Building queries for range 8565-9554
14891 [2017-11-04 16:01:08.642] [background] [info] - Building queries for range 9556-9886
14891 [2017-11-04 16:01:08.642] [background] [info] - Building queries for range 9888-9984
14891 [2017-11-04 16:01:08.642] [background] [info] - Building queries for range 9986-11556
14891 [2017-11-04 16:01:08.642] [background] [info] - Building queries for range 11558-12398
14891 [2017-11-04 16:01:08.642] [background] [info] - Building queries for range 12400-12872
14891 [2017-11-04 16:01:08.642] [background] [info] - Building queries for range 12874-13136
14891 [2017-11-04 16:01:08.642] [background] [info] - Building queries for range 13138-13772
14891 [2017-11-04 16:01:08.642] [background] [info] - Building queries for range 13774-13935
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 13938-14127
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14129-14132
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14134-14179
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14182-14201
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14203-14212
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14214-14264
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14266-14295
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14299-14308
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14314-14319
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14321-14321
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14323-14324
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14327-14327
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14329-14330
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14332-14335
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14337-14340
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14343-14344
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14348-14352
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14354-14354
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14356-14357
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14362-14370
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14372-14387
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14395-14397
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14401-14401
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14403-14404
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14416-14416
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14419-14419
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14427-14427
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14458-14458
14891 [2017-11-04 16:01:08.643] [background] [info] - Building queries for range 14460-14463
14891 [2017-11-04 16:01:08.643] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.647] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.651] [background] [info] -- Unlinking "<E-Mail Subject>" (Vkg5FSorEYu91SKPSUgZw763tAFfbqBceugTntnbM)
14891 [2017-11-04 16:01:08.655] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.661] [background] [info] -- Unlinking "<E-Mail Subject>"  (odc5zR6twSEyCR2J12Zi9xYyenH4jq637c2Tpfezi)
14891 [2017-11-04 16:01:08.662] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.666] [background] [info] -- Unlinking "<E-Mail Subject>" (hu51ZfQwkJSukJE6aaPFenTJbmsacKEkohgcWVyXQ)
14891 [2017-11-04 16:01:08.668] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.676] [background] [info] -- Unlinking "<E-Mail Subject>" (hhRDvpEFoe8sA7vyjqnkS9jBPnW13uDD6yYvco6Z7)
14891 [2017-11-04 16:01:08.678] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.681] [background] [info] -- Unlinking "<E-Mail Subject>" (Rfq4CQ4wA6RRshDSncm2c5b37a9WckKRyvhd2xJLs)
14891 [2017-11-04 16:01:08.682] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.689] [background] [info] -- Unlinking "<E-Mail Subject>" (235puu9g2n1gweNZeSoa4PK51utugebCLtyTps5LL)
14891 [2017-11-04 16:01:08.690] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.694] [background] [info] -- Unlinking "<E-Mail Subject>" (JovfASkJfgKNdiCNEsQNYj7GS1L9tSSBg3rthdAc6)
14891 [2017-11-04 16:01:08.694] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.697] [background] [info] -- Unlinking "<E-Mail Subject>"  (EdVPkpmBkeAXhCzns359UK463D6Hxz4fnziXwJpdA)
14891 [2017-11-04 16:01:08.698] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.704] [background] [info] -- Unlinking "<E-Mail Subject>" (F36Zhr5iNCoiMy9cWFjhbe8zx63c8ewUcDVw4kGbP)
14891 [2017-11-04 16:01:08.707] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
14891 [2017-11-04 16:01:08.710] [background] [info] -- Unlinking "<E-Mail Subject>"  (btLx78YRqaqt17hBdiiQARwwYZEHj61c5Es1kZnwf)
14891 [2017-11-04 16:01:08.711] [background] [info] -- Unlinking "<E-Mail Subject>"  (mFLxTuTJk79fLp25C54Umg7DzxMZ9XxaK67bUJ3XX)
14891 [2017-11-04 16:01:08.712] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
14891 [2017-11-04 16:01:08.716] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
14891 [2017-11-04 16:01:10.260] [background] [info] syncFolderChangesViaCondstore - Sent: highestmodseq, uidnext match, no changes.
14891 [2017-11-04 16:01:10.401] [main] [info] [local-799dc461-94b3] Running ChangeFolderTask performLocal:
14891 [2017-11-04 16:01:10.429] [main] [info] [local-799dc461-94b3] -- Succeeded. Changing status to `remote`
14891 [2017-11-04 16:01:10.477] [foreground] [info] Idle exited with code 0
14891 [2017-11-04 16:01:10.478] [foreground] [info] [local-799dc461-94b3] Running ChangeFolderTask performRemote:
14891 [2017-11-04 16:01:10.642] [foreground] [info] [local-799dc461-94b3] -- Succeeded. Changing status to `complete`
14891 [2017-11-04 16:01:10.643] [foreground] [info] Idling on folder INBOX
14891 [2017-11-04 16:01:10.832] [background] [info] Could not save file data!
14891 [2017-11-04 16:01:11.078] [main] [info] [local-5fab371e-3a5a] Running ChangeUnreadTask performLocal:
14891 [2017-11-04 16:01:11.079] [main] [info] [local-5fab371e-3a5a] -- Succeeded. Changing status to `remote`
14891 [2017-11-04 16:01:11.121] [foreground] [info] Idle exited with code 0
14891 [2017-11-04 16:01:11.121] [foreground] [info] [local-5fab371e-3a5a] Running ChangeUnreadTask performRemote:
14891 [2017-11-04 16:01:11.165] [foreground] [info] [local-5fab371e-3a5a] -- Succeeded. Changing status to `complete`
14891 [2017-11-04 16:01:11.165] [foreground] [info] Idling on folder INBOX
14891 [2017-11-04 16:01:11.264] [background] [info] Could not save file data!
```
</details>

<p></p>

All of these unlinked emails are still in the Inbox on the server, and I didn’t do anything with them. I have no clue why the sync engine decides to remove them.

I don’t want to make my whole logfile public, but I would email it do anyone wanting to investigate the issue.

##### Are there any related issues?
#230 could be related, or even the same. I’m not sure.

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
v1.0.7

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes, I could only observe it with my personal IMAP account.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I don’t think it’s specific to certain messages.

¹ I have removed the emails' subjects from the log and replaced them with `<E-Mail Subject>`

**Comment by jGleitz** [comment]
Clearing the cache reproducibly retriggers the issue: first, all Mails are there, but they disappear shortly after. The log contains the same lines and the same few messages stay in the Inbox.

**Comment by tuxtard** [comment]
Confirmed. While sync is running all messages are there. When sync procedure is completed almost everything is gone, only few messages are left in the Inbox. This happens on v1.0.7, both Windows and Mac. Server is Zimbra IMAP.

**Comment by bengotow** [comment]
Hey folks—hmm, this is really interesting. The way Mailspring connects to IMAP, it expects to find each message in exactly one remote folder. If it scans a folder and finds an existing email there from another folder, it assumes the email was moved. Because it always scans your inbox first and then moves on to other folders, "virtual folders" would definitely cause this problem. 

When you use Virtual Folders, most mail clients just duplicate the message and copies in both folders locally, but features like snoozing and read receipts rely on Mailspring being able to uniquely track a message as it's moved without forgetting that it's the same object, so we have the move concept.

I actually didn't know Dovecot or Zimbra used virtual folders though — could you elaborate on your configuration a bit? The only case of virtual folders I know of is Gmail, where it represents each label as a virtual folder, but Mailspring avoids issues with that by only syncing the All Mail, Spam and Trash folders and using the X-GM-LABELS extension to get labels the more correct way.

I'm not sure there's a quick fix for this, but at the very least we could make it so you can disable syncing some folders so Mailspring doesn't get confused and move everything out of your inbox.

**Comment by bynicolas** [comment]
Actually, Dovecot virtual folders work similarly to Gmails labels.  Virtual folders are simply instructions set in a `dovecot-virtual` file that classify mail. So mail is not actually copied over but simply filtered into the virtual folder.

You can get more info here https://wiki2.dovecot.org/Plugins/Virtual

I know I personally use an `All mail` virtual folder a bit like in Gmail, but this set up might not be present on all Dovecot installations. So I'm not sure how you could set this up as a permanent fix, but I might be able to help out testing some scenarios with Dovecot.

@bengotow, you can message me on slack for further discussion.

**Comment by jGleitz** [comment]
@bynicolas I’m not sure that your assessment is entirely correct. I don’t use `dovecot-virtual` (but I use dovecot), and for my setup, the assessment that any email is contained in exactly one folder should hold. So @bengotow, I think there is another issue causing this.

**Comment by tuxtard** [comment]
@bengotow It happens on default Zimbra setup. I am not sure if Zimbra uses virtual folders by default, I will try to find out.

**Comment by jeremyj** [comment]
Hi All,
same problem here: empty Inbox using Dovecot without virtual folders.
BTW the messages didn't disappear immediately but a few days after setting up Mailspring.

**Comment by bynicolas** [comment]
@jGleitz and @jeremyj reporting that they don't use virtual folders really looks like the issue is related to something else.

@bengotow Is there any way to troubleshoot this (maybe with Xcode tools). This issue renders Mailspring pretty much unusable. So if it's possible to have deeper debugger logs, and narrow down the issue let me know.

**Comment by jeremyj** [comment]
Hey,
just adding some hopefully useful info.
My IMAP server setup is with Dovecot 2.2.22  (from Ubuntu 16.04.2 LTS). I do not use the "virtual" plugin as described in @bynicolas 's link.

**Comment by jGleitz** [comment]
I think we collected enough evidence to say that this issue is *not* specific to virtual folders. I renamed the issue to reflect that it is a general incompatibility with certain mail server setups.

**Comment by jeremyj** [comment]
FYI my problem seems to have been solved by resetting the email cache in the Mailspring settings.
I will update you if the problem happens again.

**Comment by bynicolas** [comment]
Negative for me. Resetting the cache doesn't solve it.

I guess that if you use virtual folder, the issue comes from when Mailspring see the email in the virtual folder and then removes it from inbox because it think it's a duplicate.

For those who don't use virtual folders, I have no clue!

**Comment by Bergg** [comment]
Same issue here with IMAP, on a fedora box. The "rebuild cache" gets unread messages back, and after a few minutes, all email with arrival dates later than today disappear.

**Comment by bynicolas** [comment]
Has there been a fix?

For some reason I have mail that stick in my inbox since a few hours. Which for me is new!

Any body else can confirm this?

**Comment by bynicolas** [comment]
Ok, I had some time to test my hypothesis regarding virtual folders.

Now this issue is pretty annoying rendering Mailspring unusable for me, and some of you are reporting issues **without** using dovecot virtual folders which complicates the issue even further.

So for you guys not using virtual folder, I have no idea what the issue might be .

### Disabling Dovecot virtual folders
As for me, I think I made progress in debugging the issue. I disabled dovecot virtual folders and cleared my Mailspring cache.

upon resync, all my mail is within Mailspring inbox folder.

So I can assume the issue in my case (and other using virtual folders) is that Mailspring will remove a message it finds a duplicate email in any other virtual folder.

There should be a fix for this.  Why is it working with Gmail but cannot work with dovecot, zimbra, etc.?

I'm not familiar with zimbra, but my guess is that if it's using some kind of virtual classification of email (as labels or something of that nature) then the issue might be the same: if mailspring finds a *duplicate* email within another folder/label/whatsoever it will remove it from the inbox since it needs to uniquely match an email to make use of some features such as snoozing.

As for my previous comment, I don't know why some mail didn't get removed from the inbox.  I haven't dug deep enough to understand that but my guess is that it might have removed it from the virtual folder in the case of those few email that stuck in the inbox. But that is purely speculation at this point!

@bengotow, you are pretty quiet on this issue... is there anything we can do to help out?

**Comment by Bergg** [comment]
I just refreshed to 1.0.12 (113) and emails keep disappearing afer a little while, so no change there.

**Comment by Alconqro** [comment]
I have the same issue with a zimbra 7 mail server, Mailspring is running in Ubuntu 16.04

**Comment by miracle2k** [comment]
I am using mail-in-a-box and also have this issue.

**Comment by Bergg** [comment]
So frustrating.. not sure what I can do to help out with this issue but I'm avaialble to do so.

**Comment by jdavidbakr** [comment]
Getting the same here, using my own dovecot/postfix setup.  Mail reappears after clearing cache.  Running in Ubuntu Budgie 17.10.  I have mailspring running on my old Mac as well, and also have my iPhone + a version of Mac Mail accessing my mailbox.

**Comment by jdavidbakr** [comment]
Anything I can do to help troubleshoot, I'd be happy to.  Getting a little tired of having to clear the cache several times per day, but besides this bug I much prefer Mailspring to any other mail alternative I have found.

**Comment by jo-chemla** [comment]
Also clearing the cache several times a day for emails to re-appear in inbox, subscribing to notifications.

**Comment by Bergg** [comment]
Clearing the cache turns my pc into a heater with all fans blazing for more than an hour so I'm using nylas again..

**Comment by otobrzo** [comment]
I have the same issue, after initial setting inbox is ok but once it finished scanning of all folders the inbox is suddenly empty. I thing that the possibility to subscribe selectively folders will solve this issue. For instance, I have mboxbackup file which has the same content as inbox and thus mailspring is confused.

**Comment by Bergg** [comment]
This it what's in the log when the emails disappear

`24380 [2018-04-04 17:35:43.840] [background] [info] Sync loop deleting unlinked messages with ph
ase 2.
24380 [2018-04-04 17:35:43.860] [background] [info] -- Removing 100 unlinked messages
24380 [2018-04-04 17:35:44.088] [background] [info] -- Removing 100 unlinked messages
24380 [2018-04-04 17:35:44.340] [background] [info] -- Removing 100 unlinked messages
24380 [2018-04-04 17:35:44.502] [background] [info] -- Removing 100 unlinked messages
24380 [2018-04-04 17:35:44.736] [background] [info] -- Removing 100 unlinked messages
24380 [2018-04-04 17:35:44.941] [background] [info] -- Removing 100 unlinked messages
24380 [2018-04-04 17:35:45.347] [background] [info] -- Removing 100 unlinked messages
24380 [2018-04-04 17:35:45.516] [background] [info] -- Removing 100 unlinked messages
24380 [2018-04-04 17:35:45.937] [background] [info] -- Removing 100 unlinked messages
24380 [2018-04-04 17:35:46.098] [background] [info] -- Removing 100 unlinked messages
24380 [2018-04-04 17:35:46.378] [background] [info] Sync loop complete.`

**Comment by fonsocm** [comment]
Same problem with Zimbra server and OpenSuSE Leap 42.3.

**Comment by rafaelrenanpacheco** [comment]
> Same issue here with a Zimbra IMAP, on a fedora box. The "rebuild cache" gets unread messages back, and after a few minutes, all email with arrival dates later than today disappear.

Got this exactly same behavior here as well. Using Zimbra as mail server and running Mailspring 1.2.1 on Arch Linux.

**Comment by anotherZero** [comment]
I thought I'd mention that I'm having the same issue here.  Is there a workaround or fix on the horizon?

**Comment by Bergg** [comment]
My workaround is going back to Nylas Mail (it still works) until this gets fixed.

**Comment by MattiaCostamagna** [comment]
Hi there! Has someone managed to solved this issue? I'm new to Mailspring and this happens to me too

**Comment by Bergg** [comment]
I read in #974 that @bengotow announces a new release, perhaps this specific issue will be addressed in it.

**Comment by therecluse26** [comment]
Same issue, but on Mac and connecting to an Outlook 365 account. It only seems to happen on specific emails (one I sent to myself as a reminder, in particular). If have to re-sync and then it comes back but then disappears again after a while.

**Comment by rafaelrenanpacheco** [comment]
The issue is not resolved for me as well, I'm using version 1.4.2. E-mails disappears from inbox, being necessary to rebuild the cache all the time.

**Comment by medhabibdhif** [comment]
I'm facing the same problem on Zimbra IMAP.

**Comment by dinoboy197** [comment]
Also seeing this issue with emails appearing and disappearing from inbox without warning. Clearing email cache does not help at all. Using Zoho IMAP email, no virtual folders, version 1.4.2-f587b7b7 on Ubuntu Linux 18.04.

**Comment by nemm** [comment]
At least once a day some of my messages disappear. I can tell by the number of unread messages in inbox, that suddenly just changes and after that I cannot find does unread messages. Rebuilding cache helps.

**Comment by great-qwerty** [comment]
Same here, Ubuntu 18.04 + Mailspring 1.4.2-f587b7b7 + Office 365.

**Comment by bvergnaud** [comment]
Same here on Arch Linux, with Mailspring 1.4.2-f587b7b7 and Zimbra.

**Comment by romintomasetti** [comment]
Have the same issue with the last version of Mailspring for Ubuntu 18.04. The mail server is a IMAP powered by Zimbra.

**Comment by darkameba** [comment]
I have this issue with iCloud. It's a show stopping bug. I wish this would be addressed because I really like Mailspring but it's pretty much useless to me until this is fixed.

**Comment by mirkoschubert** [comment]
Same here. I have installed Mailspring (the current version) on Windows 10 (the current version) for a friend. He has two accounts - one is iCloud, one an IMAP account on a own server (on a German Webhoster). All mails in the INBOX on both accounts disappear after a while. Resetting the cache helps - even when he does it only in the iCloud account. But only for the moment...

I on the other hand don't have any problems on macOS Mojave whatsoever. 😏

**Comment by blietaer** [comment]
Same here. 

- Dual booting between Win10 and Manjaro (but 2 instances of MailSpring are not sharing the same directory) and similar behaviour on both platforms. 

- Actually I though it was a 'features', old read mail hidden/moved somewhere, but I just can't find them at all. 
 
- 2 gMails and 1 classic IMAP accounts and when I connect to the respective webmails, everything is there...

Pitty.

I really love Mailspring, won't drop it for that...but please fix this quickly ? :)

**Comment by MattiaCostamagna** [comment]
I noticed that sometimes when I click "Process entire inbox" in the "Mail rules" settings I have to rebuild the cache too because I can't see any e-mail anymore.

**Comment by blietaer** [comment]
This now becomes a real showstopper, I am afraid... :/
Any chance this could get fixed soon?
I am afraid I'll have to ditch MailSpring on both Linux and Windows.

Any workaround? does it make sense to properly uninstall it and install the latest version 'from scratch' ?
(e.g. corrupted cache/config that would keep on contaminating versions updates ? )

THx.

**Comment by cpacchierotti** [comment]
I am experiencing the same issue with Zimbra IMAP server (on Fedora).

**Comment by M-Pixel** [comment]
November 2017 - that's a **long** time for such a major bug to go unaddressed by the author, especially for a paid product.  I subscribed, despite feeling the price was really high for what you get, hoping to help the development of what looked like a cool product.  But now seeing that something this major can go unaddressed for over a year on what should be a very good full-time salary (assuming it has at least a thousand subscribers), I have every reason to believe that Mailspring will never reach a stable state.  I'm going to start seeking out an alternative, and cancel my subscription as soon as I settle on one.

**Comment by xclabit** [comment]
I have yet to experience this on MailSpring yet but I did encounter this in Nylas N1 so I'm worried this is a major problem that has been carried over and I feel this is something that I will probably experience soon if I continue to use MailSpring. It's definitely a concern that it still has not been addressed yet. I'm also very disappointed in the reply provided in: https://github.com/Foundry376/Mailspring/issues/1096#issuecomment-427746123

in which Ben expressed that he has been working on localization of the app, and his plan to work on making a public gallery/community for themes. Quite honestly, those are not high-priority items compared to this issue. If I were a paid user (was very close to being one until I started reading these issues here), I'd definitely be very upset with this development direction considering that the paid service is very expensive, and doesn't really offer much. Furthermore, the app is still incomplete as it is lacking proper contacts management (big minus for me) and calendar management.

But it seems the app has yet to even get proper mail functionality.

**Comment by levelmeasure** [comment]
Installed MailSpring on a Mac two weeks ago. Email disappeared from the Inbox for the company domain account, but email in Gmail account is still there. Resync has not resolved the issue. Has anyone found the solution to this problem?

**Comment by cpacchierotti** [comment]
"Rebuild Cache" should resolve the issue for around 10-20 minutes. However, after that, the emails will disappear again.

Do you know which mail server is used by your company? Can you attach the relevant part of your log?
Is it similar to https://github.com/Foundry376/Mailspring/issues/304#issuecomment-461361238?

**Comment by levelmeasure** [comment]
I don't know what email server is being used by my provider. I see no email delivery errors.

**Comment by cpacchierotti** [comment]
Under Developer>Open MailSync logs, you will find a text file named, e.g., mailsync-487XXXXa.log. You will see one .log file per account (select the one from which the emails disappear).

Do the "Rebuild Cache," then wait for the emails to disappear, and finally check the end of the log (the most recent lines).

**Comment by levelmeasure** [comment]
Server side email software is Dovecot Server for IMAP and EXIM as the SMTP server. This is the default implementation of cPanel. Will have to wait to check logs at the end of the day.

**Comment by cpacchierotti** [comment]
Indeed, as you can see from the other posts, this seems an issue affecting Dovecot and Zimbra servers. Unfortunately, it affects several people (especially business users) and there is no solution. You can try to "Rebuild Cache" every time it happens, but it is quite annoying.

@bengotow : please let us know if there is something you may need from us to debug this issue. Do you think you will be able to work on this any time soon or should we better use some other software in the meantime?

**Comment by cpacchierotti** [comment]
Still present in 1.5.6.

**Comment by busseyl** [comment]
I'm running 1.5.6 on my Mac and Linux (Ubuntu). This issue exists on both.

In Linux I have a number of email accounts and I haven't isolated which one exactly is affected (perhaps all).

On my Mac I have only a single IMAP email account with the hosting provider Zoho Mail.

I'm not using folders for these accounts, I keep everything in Inbox and archive the messages that I don't need immediately available.

Looking forward to a solution!

**Comment by cpacchierotti** [comment]
It would be useful to isolate which account is affected. Look on the logs and search something like https://github.com/Foundry376/Mailspring/issues/304#issuecomment-461361238. Unfortunately, I don't expect a solution any time soon (this issue is already more than 1 year old).

**Comment by cpacchierotti** [comment]
This issue is still present in 1.5.7.

```
2989 [2019-02-26 08:03:41.257] [background] [info] - Building queries for range 48432-48509
2989 [2019-02-26 08:03:41.257] [background] [info] - Building queries for range 48513-48646
2989 [2019-02-26 08:03:41.257] [background] [info] - Building queries for range 48649-48660
2989 [2019-02-26 08:03:41.257] [background] [info] - Building queries for range 48662-48709
2989 [2019-02-26 08:03:41.257] [background] [info] - Building queries for range 48711-48714
2989 [2019-02-26 08:03:41.257] [background] [info] - Building queries for range 48716-48833
2989 [2019-02-26 08:03:41.258] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.259] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.259] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.259] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.259] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.260] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.260] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.261] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.261] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.261] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.261] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.262] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.262] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.263] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.263] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.263] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.263] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.264] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.264] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.265] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.265] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.266] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.266] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.267] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.267] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.267] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.268] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.268] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.268] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.269] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.269] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.270] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.270] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
2989 [2019-02-26 08:03:41.272] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.272] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
2989 [2019-02-26 08:03:41.273] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.273] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
2989 [2019-02-26 08:03:41.274] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.275] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
2989 [2019-02-26 08:03:41.276] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.276] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
2989 [2019-02-26 08:03:41.277] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.277] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
2989 [2019-02-26 08:03:41.278] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.278] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
2989 [2019-02-26 08:03:41.279] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.311] [background] [info] syncFolderChangesViaCondstore - Trash: modseq 71529 to 71529, uidnext 48834 to 48834
2989 [2019-02-26 08:03:41.336] [background] [info] syncFolderChangesViaCondstore - Junk: modseq 71532 to 71537, uidnext 48834 to 48840
2989 [2019-02-26 08:03:41.452] [background] [info] syncFolderChangesViaCondstore - Changes since HMODSEQ 71532: 1 changed, 48833 vanished
2989 [2019-02-26 08:03:41.453] [background] [info] - Building queries for range 1-46743
2989 [2019-02-26 08:03:41.453] [background] [info] - Building queries for range 46745-46940
2989 [2019-02-26 08:03:41.453] [background] [info] - Building queries for range 46942-47358
2989 [2019-02-26 08:03:41.453] [background] [info] - Building queries for range 47360-47986
2989 [2019-02-26 08:03:41.453] [background] [info] - Building queries for range 47988-48562
2989 [2019-02-26 08:03:41.453] [background] [info] - Building queries for range 48564-48838
2989 [2019-02-26 08:03:41.453] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.454] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.454] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.455] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.455] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.456] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.456] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.456] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.456] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.457] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.457] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
2989 [2019-02-26 08:03:41.458] [background] [info] -- 0 matches.
2989 [2019-02-26 08:03:41.479] [background] [info] syncFolderChangesViaCondstore - Archives: modseq 69610 to 69610, uidnext 48015 to 48015
2989 [2019-02-26 08:03:41.502] [background] [info] syncFolderChangesViaCondstore - Archives/2017: modseq 69437 to 69437, uidnext 47877 to 47877
2989 [2019-02-26 08:03:41.525] [background] [info] syncFolderChangesViaCondstore - Archives/2018: modseq 69453 to 69453, uidnext 47929 to 47929
2989 [2019-02-26 08:03:41.547] [background] [info] syncFolderChangesViaCondstore - Archives/2019: modseq 71535 to 71535, uidnext 48826 to 48826
2989 [2019-02-26 08:03:41.571] [background] [info] syncFolderChangesViaCondstore - Mailspring: modseq 52160 to 52160, uidnext 30554 to 30554
2989 [2019-02-26 08:03:41.593] [background] [info] syncFolderChangesViaCondstore - Mailspring/Snoozed: modseq 52163 to 52163, uidnext 30556 to 30556
2989 [2019-02-26 08:03:41.594] [background] [info] Sync loop deleting unlinked messages with phase 2.
2989 [2019-02-26 08:03:41.607] [background] [info] -- Removing 34 unlinked messages

```

**Comment by itk-union** [comment]
seems to be an old post but still active, same for me on MailSpring 1.5.7-2057ca30

**Comment by ShanethPatterson** [comment]
This issue is still affecting me, on 1.5.7-2057ca30.

**Comment by therecluse26** [comment]
I hate to be rude, but I'm amazed that this is still an issue, honestly. Such a major bug being completely unaddressed for so long would look bad on a fully free piece of software, much less one that has a paid option.

**Comment by dlj2019** [comment]
I am also having issues running on KDE Neon 18.04 ...

2481 [2019-03-11 21:22:48.173] [background] [info] - remote=0, local=0
2481 [2019-03-11 21:22:48.308] [background] [info] syncFolderUIDRange for [Mailspring]/Snoozed, UIDs: 1 - 1, Heavy: false
2481 [2019-03-11 21:22:48.447] [background] [info] - remote=0, local=0
2481 [2019-03-11 21:22:48.529] [background] [info] Sync loop deleting unlinked messages with phase 2.
2481 [2019-03-11 21:22:48.531] [background] [info] Sync loop complete.
2481 [2019-03-11 21:24:48.531] [background] [info] Syncing folder list...
2481 [2019-03-11 21:24:48.909] [background] [info] syncFolderUIDRange for INBOX, UIDs: 30531167 - 30531567, Heavy: false
2481 [2019-03-11 21:24:49.387] [background] [info] - remote=400, local=400
2481 [2019-03-11 21:24:49.687] [background] [info] syncFolderUIDRange for Sent, UIDs: 1 - 30388966, Heavy: false

**Comment by itk-union** [comment]
No answer on my support ticket at Mailspring so far...

**Comment by quixoticraindrp** [comment]
This issue: https://github.com/Foundry376/Mailspring/issues/1095 seems to be the same as the issue in this thread.

I am also seeing the same issue.
Mailspring 1.5.7-2057ca30 on macOS 10.14.3
Mailbox affected is iCloud

**Comment by bvergnaud** [comment]
@bengotow : Hi,

As I'm seeing you being active in more recent issues, I'm thinking maybe you're just not seeing this old issue anymore. I'm hoping this mention will get your attention.

Could you please acknowledge that there is a massive problem in the sync engine and tell us if you ever intend to fix it ?
Zimbra, iCloud, plain old postfix+dovecot... these are not your odd mail server stacks, they're pretty much everywhere. Both free and paying users have complained as well.

If you're just going to disregard such a blatant bug in your software, we all might as well abandon hope and find a replacement. No matter how sexy your software looks, what we all need first and foremost is a mail client that works as expected and doesn't do magic tricks with our emails.

If I don't see any news from you on that matter by the end of the month, I'll consider it the final nail in the coffin, and start looking for a replacement. It'd be a shame, but I've put up with the bug for months now and it's just not acceptable anymore, free software or not.

Thanks for all the great work you've put in so far !

**Comment by quixoticraindrp** [comment]
@bengotow: agreed, this is a total show-stopper. For me, in the iCloud inbox, Mailspring only shows messages back to the 5th of March and will go no farther back. In the Mail app on my phone, I can see the rest of the messages older than those, so it's not actually doing anything to them—at least, it seems not to be, for now.
It's not that only read or unread messages, there are some of both that are not in the Mailspring inbox, and some of both that are.
As configured, my Mailspring connects to one Gmail account, and one iCloud account.
The iCloud account is the only one affected of the two, in this way at least.

**Comment by cpacchierotti** [comment]
Unfortunately, I think that we have our answer here: https://github.com/Foundry376/Mailspring/issues/1413#issuecomment-473576017

**Comment by M-Pixel** [comment]
This issue was dismissed by the author in closed issue #1413 as being the fault of virtual folders.

I've just confirmed with FastMail, my provider, that...
> No, we don't use virtual folders; we use standard IMAP folders which should be able to be synced through any IMAP enabled client.

**Comment by itk-union** [comment]
As said, same for me. Our mailserver (on-premise) does not use virtual folders, still Mailspring won't work. Looking for alternatives.

**Comment by Bergg** [comment]
Zimbra does not appear to use virtual folders either.

**Comment by itk-union** [comment]
Really so sorry, but offboarding. Mailspring not showing mails in inbox, even some new ones missing right inbetween others that do show. Saying it's because of virtual folders - **which it definitely isn't** - and closing the ticket is not plausible to me. Search not really working either. Nice look and feel, but too far away from usable so I'll have to switch back to rotten-looking Thunderbird which at least works most of the time. Would have honestly loved sticking to Mailspring :-1: :cry:

**Comment by cpacchierotti** [comment]
Could you check your log and see if it looks similar to https://github.com/Foundry376/Mailspring/issues/304#issuecomment-467323937 ?

Thank you.

**Comment by itk-union** [comment]
> Could you check your log and see if it looks similar to [#304 (comment)](https://github.com/Foundry376/Mailspring/issues/304#issuecomment-467323937) ?
> 
> Thank you.

Sorry, I already deleted my Mailspring installation as I was a bit pissed when a premium customer of mine moaned about me not answering an email from two days ago...

**Comment by massimilianocomin** [comment]
I am suffering from this issue too : macOs 10.14.3 with MailSpring connected to Gmail and Zimbra. It seems to affect only mails from Zimbra.
This bug makes Mailspring unusable.

**Comment by Aircl0wn** [comment]
Adding IceWarp in the list of mailservers that suffer from this issue.
Afaik we don't have virtual folders configured either.

**Comment by jgardiner68** [comment]
I notice it when I clean out the Spam folder.
I am using MacOS, latest release and Google Gsuite.

The bodies of messages in Spam are not automatically downloaded but it looks like if I start deleting messages before the body has been downloaded, then sometimes the message reappears when the body has been download.   Only seems to affect messages where the body has not been previously downloaded.  Rather annoying.

**Comment by jardev** [comment]
Having the same issue with my Dovecot server. No virtual folders. Rebuilding the cache helps yet not for long. I use Mailspring on Windows, Mac and Linux. All have the same issue so I assume it could be related somehow to the backend and snoozing/reminders functionality. If I do a follow-up reply on the missing mails from another mail client then they appear back in Inbox in Mailspring. 

If the issue won't be resolved in the near future I'm going to cancel my subscription. It's annoying to have 2 different mail clients "just in case" and worry about missing mails.

**Comment by louis77** [comment]
Having the same issue, started a few days ago with iCloud emails. Except a few emails all of my inbox disappear. But I can see these messages in Apple Mail. Sad that this issue doesn't get the attentions it need, because I have to leave Mailspring because of that.

**Comment by M-Pixel** [comment]
I finally got around to cancelling my Pro subscription due to this.

**Comment by ismathibrahim** [comment]
I can't believe this issue has been unattended for nearly two years. I really want to use MailSpring for the clean ui. But what's the use if it won't let me see the emails. This problem occurs on my two pcs.

**Comment by cpacchierotti** [comment]
As you can see from https://github.com/Foundry376/Mailspring/issues/1413#issuecomment-473576017, this bug won't be fixed any time soon.

**Comment by Bergg** [comment]
still present with mailspring-1.6.1-0.1 on fedora30.

**Comment by sendittokeith** [comment]
one account each on: gmail, yahoo, mailinabox
- I constantly see emails appear and disappear from my inbox. Sometimes i click delete on a message and it doesnt go away, it makes me fear it might be deleting another email.  Most of the time new emails dont show up unless I restart the app - even then sometimes It doesnt work until I click around on several folders first.

Very flaky app - too bad because its the best looking one for linux I have found (that has unified inbox).

v1.6.1 on Elementary

**Comment by TheSHEEEP** [comment]
I am also seeing random emails disappearing. Though it happens randomly as well, not after each sync. While in Thunderbird, everything is just fine.

This is frankly ridiculous. Email clients from 10+ years ago can manage to correctly sync emails, but this one can't?
And the bug is known for a long time, and nobody bothers to fix it? Just do what Thunderbird does to sync emails then, it is open source and obviously works.

**Comment by jardev** [comment]
Too bad, it's been almost two years they can't fix this bug. It annoyed me so much that I had to switch back to Thunderbird, and I cancelled my subscription.

**Comment by yavuzaydin** [comment]
How comes this issue is still open? Is there anything we can do to help speed up the resolution of this issue besides sending a PR?

**Comment by gpetrov** [comment]
I'm just using Mailsprint for two days and suddenly got an empty inbox with just 1 last email in it ...
Other IMAP clients see full inbox - but only Mailspring not ...
Tried restarting numerous times - didn't help

I wonder why such serious issue is open for 2 years already ... it makes Mailsping pretty unusable...
Shame for such great app

**Comment by sbuschjaeger** [comment]
I have the same problem. New (incoming) mails seem to be correctly displayed, but "older" mails form the inbox keep disappearing from an IMAP account. For me this happens on both, Windows and Linux (both on mailspring 1.7.2). As far as I can tell this is not linked to virtual folders on the IMAP server.

**Comment by thorstengrothe** [comment]
I can confirm this error, here on Archlinux with mailspring 1.7.2. Messages suddenly dissappear from inbox very sad, because it's a wonderful client! Rebuilding cache solves the problem for a few minutes or so...

**Comment by gpetrov** [comment]
My problem was permanently solved by Rebuilding the Cache

**Comment by kdekooter** [comment]
Few minutes later.... is it still solved @gpetrov ?

**Comment by gpetrov** [comment]
yes @kdekooter - I'm running already for few days Mailspring continuously and the problem hasn't occur any more after the cache rebuild. Everything functions fine.

**Comment by kdekooter** [comment]
I gave the rebuild another shot. Working for me as well, sofar.

**Comment by kurisu-gh** [comment]
@gpetrov @kdekooter after about a week, is it still working well? I want to give Mailspring another shot so I started rebuilding the cache, but now experiencing a different problem (https://github.com/Foundry376/Mailspring/issues/1335).

**Comment by kdekooter** [comment]
@kurisu-gh Yes, still seeing all messages I expect to see. Also looking at an eternal scanning message..

**Comment by cpacchierotti** [comment]
In my experience, rebuilding the cache worked for 10-15 minutes. After that, the messages disappeared again.

**Comment by kdekooter** [comment]
Yes, same here, messages disappearing again.

**Comment by sbuschjaeger** [comment]
Same here. Currently messages older than 8 days are gone and back again after rebuilding.

**Comment by thosgood** [comment]
I have a few "old" (i.e. a couple of weeks old) emails in one of my inboxes that seem to just disappear entirely in Mailspring (but that are still there in other clients). It sucks, because it's the only problem I've had so far!

**Comment by simtrax** [comment]
I also have problems with emails disappearing.
As a matter of fact right in front of my eyes, I was sitting in front of the computer pondering on life with the Unread folder visible. There was about 6 emails there. All of a sudden 2-3 of them disappeared without me doing anything.
Could not find them in the client after that. Tried restarting it with no luck.
Opened mailbox in a web client, found them as unread. Toggled the unread status and they went right back in to the unread folder of Mailspring, instantaneously.

I also have issues with emails just being gone. Can be found in other clients. Mark them as unread there and they show up in Mailspring.

**Comment by thealk** [comment]
This has been happening to me recently (installed Mailspring about 3 weeks ago). It doesn't seem to occur with my inbox, but happens when I move emails to other folders. I am also able to find them with other email clients.

**Comment by pleone** [comment]
I have lots of email disappearing and being trashed ( on multiple accounts ) but of course i did not trash them.
Really annoying! :disappointed:

**Comment by wadih** [comment]
Just got a case of an email disappearing. 

It was an email I sent to myself and to another alias which redirects to myself. So I can understand the confusion in the app. However there still is one copy of the email in my inbox, and Mailspring doesn't see it, but Outlook sees it. Perhaps this is a feature I'm missing and I clicked something wrong? 

I'm on Ubuntu, and the mailserver is a regular mailbox at Rackspace. 

My guess is that it has to do with the internal Mailspring caching process getting corrupted. Because it didn't corrupt the IMAP data since Outlook still sees the email, so the issue I think is that the caching gets corrupted. Perhaps if there's a cache rebuild option, I could verify this hypothesis, if the email shows up after cache rebuild.

I know this is the hard to troubleshoot type of issues, but if you need more info or test a fix, I can assist.

**Comment by agbuckley** [comment]
This has been a problem for me in the last couple of months. Very annoying, and critical enough that I may have to ditch Mailspring. How has this been unresolved for 2,5 years??

**Comment by kurisu-gh** [comment]
The developer doesn't listen or never follows through on promises to look at issues like this with valuable log information from a number of users. I've tried to bring this issue to his attention multiple times now. I give up. I have already ditched Mailspring.

**Comment by wadih** [comment]
I also had to stop using Mailspring because of that issue. Though I don't want to bother the developer, I think so much work has gone into this, especially to create the UI, and he made a lot of this code open-source, and I can see he's fighting internally on making the rest of his creation open source (e.g. the mail sync part). I don't want to take his work for granted, I'm thankful of his attempt to create that awesome mail client, but perhaps he's overwhelmed. For me coming from 10 years of Outlook where emails essentially never disappeared or got misplaced, the Mailspring "an email might be here but not visible" world wasn't a world I wanted to move into. I wish him good luck. I'll go back to Thunderbird for now on my linux machine, and I'll check back again another time if those critical usability bugs have been resolved, because I don't trust the Mailspring engine at this point with my emails.

**Comment by kurisu-gh** [comment]
Indeed, I think what the developer has done for the most part is quite amazing. Mailspring is a beautiful, cross-platform mail client. At first glance, I was so happy with it that I almost forked out money to buy a pro subscription until I realized I couldn't find important emails, archived emails randomly re-appearing and disappearing in real-time before my eyes, problems with syncing starred emails, etc. 

Two years ago or so, the developer was adamant in that Mailspring was in a good state and that he's focusing development efforts on things like a theme gallery https://github.com/Foundry376/Mailspring/issues/1096#issuecomment-427746123. If I were a paid subscriber, I'd lose my mind that critical issues like this are not being worked on.

In the mean time, features that I regularly use such as Schedule Send are now natively supported on Office 365 both on web/desktop. I don't miss Mailspring so much anymore... maybe just the user interface.

Good luck to the developer. Mailspring has so much potential but it's broken for me.

**Comment by funkycram** [comment]
Same problem here (Mailspring 1.7.8). I need to clear the cache every day...

**Comment by hellobyron** [comment]
Same issue here (1.7.8). Been using Mailspring for a while and I love it, but I just added a new IMAP account last week and now everything randomly shows up in the inbox, and then disappears after about a minute. Can't use it - unreliable. Have to switch to another client now. Testing out a paid account to see if there is any difference...

**Comment by jgardiner68** [comment]
I have stopped using Mailspring.  Settled on Outlook on MacOS (much better than it was) and Thunderbird on Linux.

Be great if the issues with Mailspring were fixed as I do like the application.

**Comment by hellobyron** [comment]
Just tested it with my paid account and it's still the same issue. If you're paying for a service, it should at least work. Cancelling service and moving to another client asap.

**Comment by wadih** [comment]
When I first searched mail client in Ubuntu Software I got Mailspring and not Evolution, which is why I went with Mailspring at first, and almost bought it until I noticed the disappearing email issue which I couldn't live with  (see my previous mesage), but then I found Evolution is exactly what one needs on linux and it is quite mature software already.

**Comment by gnif** [comment]
wow, three years since this issue was first reported, and it's still going on. In my instance, I watched my entire inbox just disappear suddenly, however, if I do a search, it magically finds emails that are now gone/hidden. What a shame, I was starting to like Mailspring.

**Comment by gnif** [comment]
Deleting a batch of automated emails I receive each day seems to trigger this. Anything older then the batch of email deleted disappears from the inbox.

**Comment by simtrax** [comment]
Yesterday when I left work I had around 40 unread emails. Today when I opened Mailspring again there's 4 unread emails.
Somehow ~35 emails has disappeared. When using a web client the emails are all there.

This has happened a few times before. This is unacceptable, I will have to look for alternatives.

**Comment by alexanian** [comment]
I had this problem, and noticed a bunch of log lines in  `~/snap/mailspring/common/mailsync-XXXXXXXX.log` with the content:

    Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.

This (and https://github.com/Foundry376/Mailspring/issues/304#issuecomment-343464073) made me wonder whether my previous use of Geary had somehow moved those into a virtual / remote folder other than Inbox (even through it didn't look that way in the web interface). I tried:

1. Manually selecting all of the emails in my hushmail inbox and selecting "Move to... > Inbox".
2. Resetting the Mailspring cache under Edit > Preferences > Reset Cache.

This caused all of my emails to appear in my Mailspring inbox for the first time! I'll edit this comment if this doesn't turn out to be a long-term fix.

**Comment by jbbarre** [comment]
Hi, 
I observed the same issue as others with Zimbra and Mailsping 1.7.8. I've just noticed two things:
-  when I read a non-read email in zimbra then this email appears again in Mailsping. 
- If I switch the "missing" emails in non-read alternatively read  in Zimbra, then all this emails appear in Mailspring... But they disappear again after a few minutes. :( . Ijust have the emails of today and yesterday.

Still any solution for this issue?

**Comment by CodeMouse92** [comment]
Hi everyone!

Reading through the history on this issue, it looks like a mix of various problems, some of which are resolved, some of which aren't. One of the major things that has historically stopped @bengotow from addressing things like this is the sheer *wall* of issues — many of which are wishlist feature requests, questions, duplicate questions, edge-case bugs, and the like — which made notifications absolutely insurmountable.

I was brought on as the Volunteer Community Manager to help tame this backlog. We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@alexanian and @jbbarre, I could really use your help on this one! Since you're both experiencing it *in 2020*, could you please start a new thread in the Bug Reports category on our [Discourse](https://community.getmailspring.com) — or else reply to the related Thread if it's already created — so we can properly evaluate and discuss this issue?

You are welcome to link back to this issue, of course, but we need some fresh diagnostic data, preferably without having to suss it out of the 117-comment "hurry up!" chain above. I want to make sure this is among the issues to be considered and addressed in 2021, but as you can guess, we need the help replicating!

Meanwhile, we're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Comment by CodeMouse92** [comment]
https://community.getmailspring.com/t/zimbra-mailspring-sync/307
