### ISSUE TITLE
ProtonMail Bridge IMAP integration

### ISSUE THREAD

**Issue by stellarsquall** [Foundry376/Mailspring#429]
Using the newly released ProtonMail Bridge I am unable to add an IMAP account, with the error:

"Sorry, this folder does not exist. (IMAP)"

Log contents:

```
----------IMAP----------

* OK [CAPABILITY IMAP4rev1 STARTTLS AUTH=PLAIN AUTH=LOGIN ID APPENDLIMIT] IMAP4rev1 Service Ready
1 STARTTLS
1 OK Begin TLS negotiation now
2 LOGIN "photosphere@protonmail.ch" *********
* CAPABILITY IMAP4rev1 AUTH=PLAIN AUTH=LOGIN ID XSTOP APPENDLIMIT
2 OK [CAPABILITY IMAP4rev1 IDLE MOVE SPECIAL-USE ID XSTOP QUOTA APPENDLIMIT=26214400] LOGIN completed
3 LIST "" ""
* LIST (\Noselect) "/" "/"
3 OK LIST completed
4 ID NIL
* ID (support-url https://protonmail.com/support name ProtonMail vendor "Proton Technologies AG")
4 OK ID completed
ID (support-url https://protonmail.com/support name ProtonMail vendor "Proton Technologies AG")
��5 LIST "" "*"
�H�Y|� 
```
The Bridge is required to provide a decryption mechanism for ProtonMail. I've followed the instructions that might apply to a Thunderbird account, found here:

https://protonmail.com/bridge/thunderbird-mac#3e

##### Are there any related issues?

Question was originally asked in closed Issue #367, with another user experiencing the same issue. 

##### What operating system are you using?

OSX 10.11.6

##### What version of Mailspring are you using?

Version 1.0.10 (1.0.10)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

ProtonMail Bridge

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Might be a feature request, considering Mailspring seems to think that there aren't any selectable folders in the account. The bridge appears to be connecting as expected, and the Thunderbird works as expected.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - when you view the account in thunderbird, does it show any sort of folders or "namespaces" for the account? Basically Mailspring is requesting a list of folders and getting nothing back:

```
3 LIST "" ""
* LIST (\Noselect) "/" "/"
3 OK LIST completed
```

I suspect we need to change what we're asking for somehow, but I'm not sure.

**Comment by stellarsquall** [comment]
Thanks for the response @bengotow!

I'm now starting to understand the log. In the sidebar for thunderbird I see the following account heirachy:

<img width="196" alt="mailspring_protonbridge" src="https://user-images.githubusercontent.com/3299840/33866637-17f1c46e-deb5-11e7-8a8b-b82b73db77ea.png">

Inside of thunderbird's account settings for local folders, I can browse the location of the local folders on disk and see the following:


<img width="1006" alt="screen shot 2017-12-11 at 8 54 28 pm" src="https://user-images.githubusercontent.com/3299840/33866738-9c8b3854-deb5-11e7-93ea-c4fc9ea29be4.png">

**Comment by durch** [comment]
+1 for this it would be great to have it, I currently have ProtonMail bridge connected to Apple Mail, and can help troubleshooting/testing...

**Comment by bengotow** [comment]
Hey folks - thanks for the extra info. I've emailed protonmail to see if they can help investigate this (since Mailspring uses Mailcore2, which is pretty popular, this might impact other clients as well.) I'll see if I can reproduce the issue and keep you posted.

**Comment by bengotow** [comment]
Just a quick update about this. I signed up for a paid protonMail account and setup the IMAP Bridge. It looks like Mailspring / Mailcore2 is unable to parse ProtonMail's response to the `ID` command, which causes failures downstream when it tries to make the next command (LIST).

Here's ProtonMail's response alongside a readable response from Gmail:

```
Works:
* ID ("name" "GImap" "vendor" "Google, Inc." "support-url" "https://support.google.com/mail" "version" "gmail_imap_171205.10_p0" "remote-host" "2601:640:4:b0f7:c175:9442:6f47:7ad3")\r\n

Fails:
* ID (support-url https://protonmail.com/support name ProtonMail vendor "Proton Technologies AG")\r\n
```

I think the problem is that ProtonMail's response isn't enclosing the values in quotes. Looking over the spec (https://tools.ietf.org/html/rfc2971#ref-IMAP4rev1) it's unclear whether the quotes are supposed to be required (though all the examples show quotes). I think it'd be a good idea for ProtonMail Bridge to change this behavior, but in the meantime I'll see if I can fix the parsing issue or find a workaround.

**Comment by stellarsquall** [comment]
Thanks for your work on this @bengotow. 

It appears that ProtonMail Bridge 1.0.1 now allows me to add the account. However I'm not able to import any messages, with the "status" for the account stating "Scanning messages". The scanning attempt eventually times out with "Encountered an error while syncing" the account.

Attached is the log for reference.

[mailsync-6cd75d34.log](https://github.com/Foundry376/Mailspring/files/1580755/mailsync-6cd75d34.log)

**Comment by ploum** [comment]
Hi @bengotow,

If you don't want to pay, I can offer you a mail account under one of my domain which is hosted by ProtonMail.

As a contribution,  I also offer to reimburse what you had to pay only to test this bug.

**Comment by bengotow** [comment]
Hey! Thanks for the reply—I've actually signed up for a paid ProtonMail subscription and reproduced the problem locally, but after doing the investigation above I've decided to wait to see if the ProtonMail folks fix this. I think they should, as this probably breaks other clients as well. The parsing code we'd need to change in mailcore2 is /very/ well tested with other providers but has no specs, so I'm fairly afraid of breaking other scenarios I don't know about in the process of fixing this.

**Comment by ploum** [comment]
You will be interested by https://www.reddit.com/r/ProtonMail/comments/7nn1vh/what_are_the_mail_clients_compatibles_with_the/

Anyway, my offer to have a ProtonMail account on one of my domain stand if you need it later and you cancelled your subscription.

**Comment by asim-vax** [comment]
Not sure if this belongs here or in another ticket - however it's the same as @kkinder 
Linux snap mailspring 1.1.4
using the linux beta bridge it can successfully connect to thunderbird, and connects fine in mailspring, pulls all correct folders/labels - however it gets stuck on creating required mailspring folders

25339 [2018-02-20 14:33:27.180] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorSubscribe
25339 [2018-02-20 14:33:27.180] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorSubscribe
25339 [2018-02-20 14:33:27.185] [background] [info] Syncing folder list...
25339 [2018-02-20 14:33:27.186] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorSubscribe
25339 [2018-02-20 14:33:27.186] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorSubscribe
25339 [2018-02-20 14:33:27.191] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 282, Heavy: true
25339 [2018-02-20 14:33:27.199] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
25339 [2018-02-20 14:33:27.202] [foreground] [info] Idling on folder INBOX

**Comment by uipoet** [comment]
@bengotow The current problem is that Mailspring attempts to create a top-level `Mailspring` folder, which Protonmail forbids. The highest level with write access is `Folders`. So for Mailspring to support Protonmail, you must change the container folder to `Folders/MailSpring`.

**Comment by Tehnix** [comment]
Failing to create the folders is also the problem with Airmail support, I believe. If it could either be turned off, or allow the user to manually set it up the folders, that should probably work.

**Comment by mitchazj** [comment]
Any update here? I would really love to see this integration happen if possible 😇

**Comment by nocriw** [comment]
Same here! Would love to help on this if needed

**Comment by armaccloud** [comment]
Here too, I'm using Protonmail Plus + Mailpring. Same errors in the logs.
Looks like something that might be fixed at Protonmail?

**Comment by leebutler** [comment]
I got excited about another mail client option for ProtonMail Bridge until I hit this issue (also stopped me from using Airmail). Please add an option to change the folder used for MailSpring metadata sync or an option to turn it off completely. I will signup for the Pro plan if this issue is fixed...

**Comment by joekendal** [comment]
Same issue. Looks like this is a simple fix

**Comment by rgruesbeck** [comment]
It will be a glorious day when this is fixed

**Comment by armaccloud** [comment]
The bug update from the side of ProtonMail I received doesn't bring much clarity on specific timelines and whether mailspring will be supported unfortunately. Hopefully something will be done on the side of Mailspring.

> Hi Arno,
> 
> Thanks for the message.
> 
> We're aware of this, unfortunately at this time other email clients (other than Outlook, Apple Mail and Outlook) are currently not officially supported, our team is trying to implement support for new email clients. 
> 
> Let us know if you need anything else. 
> 
> Best Regards,
> The ProtonMail Team

**Comment by ams-123** [comment]
Has anyone tried with the latest Mailspring?

**Comment by asim-vax** [comment]
Yep, still the same issue:
```
4801 [2018-06-01 11:21:19.146] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorSubscribe
4801 [2018-06-01 11:21:19.147] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorSubscribe
```

**Comment by ewauq** [comment]
Checked today, this is not fixed. Please make it happen 🙏

**Comment by armaccloud** [comment]
I have checked with the new protonmail bridge on Linux that just came out (v1.0.5); it's still not working unfortunately.

**Comment by 54** [comment]
Just ran into this today on the latest version of ProtonMail Bridge for Windows (1.0.5). Would be great to see the folder issue resolved at some point.

**Comment by ivanakimov** [comment]
Same. Such a shame doesn't work with ProtonMail Bridge...

**Comment by ayush-sharma** [comment]
This bug still exists with ProtonMail bridge for Linux (1.0.6_2). MailSpring is still "scanning". The mail account gets added successfully but the mail is not downloaded. Sometimes the connection will fail for now reason. The same bridge is working fine with Thunderbird.

**Comment by ayush-sharma** [comment]
Is there an update on this? I'm still not fully using Mailspring because it doesn't work with ProtonMail. Would like to switch and stop paying for AirMail, but I can't because of this bug.

**Comment by bengotow** [comment]
Hey folks—gave this another shot this evening. Unfortunately, it seems like there are still some parsing issues that are blocking ProtonMail Bridge from working with Mailspring. (It also can't create the Mailspring/Snoozed folder, but that error in the logs isn't a show-stopper). The real killer is this one:

```
11729 [2018-10-15 23:45:48.669] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
```

I was hoping the Proton Mail folks would fix the issue since mailcore2 (which is producing that underlying `ErrorParse` message) is used in a handful of other mail clients, but maybe not. I'll see if I can poke around and narrow this down a bit more.

**Comment by bengotow** [comment]
Was able to make some more progress on this—ProtonMail is still sending unquoted string literals in places where Mailcore2 expects them to be double-quoted. (For example, in the text below, the subject is quoted but the sender name ProtonMail is not:

```
* 1 FETCH (UID 1 FLAGS (\\Seen \\Flagged nonjunk) ENVELOPE (\"Thu, 14 Dec 2017 11:50:32 -0800\" \"How to get help and support\" ((ProtonMail NIL support protonmail.ch)) ((ProtonMail NIL support protonmail.ch)) () ((NIL NIL bengotow protonmail.com)) () () \"\" \"\") BODY[HEADER.FIELDS (REFERENCES)] {539}\r\n
```

I was able to expand libetpan's `mailimap_quoted_parse` method to handle this scenario (just read until we reach a control character or space), and sync ProtonMail messages in to Mailspring. It looks like ProtonMail's IMAP interface makes really heavy use of "virtual folders", (#309) and also doesn't have a synced IMAP Drafts folder, so there are some more todos before this will really work.

**Comment by Svarto** [comment]
Excitingly following this thread - thanks a lot for all the hard work!

**Comment by asim-vax** [comment]
Thank you for your continued work on this! I can now sync messages and send messages :)

**Comment by michaeltieso** [comment]
ProtonMail Bridge Version 1.1.0 finally syncs!

**Comment by asim-vax** [comment]
I would advise against trying this for the time being - it seems to have removed all mail from their folders/labels/inbox in the web portal/client. Only way to see messages is in "all mail" in web client

**Comment by armaccloud** [comment]
For me the mails in inbox/sent do sync, but new mails don't appear. Also the custom folders show, but mails don't sync. A little step intot he right direction, but not there yet.

**Comment by d2dyno** [comment]
I can only get Bridge to send mail, not sync/receive new mail from the inbox. Hoping for continued work on this :)

**Comment by maetthew** [comment]
I'd just like to mention I'm experiencing same problems. Before founding this specific issue I added some information to #890 - it's probably nothing new, just referencing it here just in case.

**Comment by fbruetting** [comment]
> Was able to make some more progress on this—ProtonMail is still sending unquoted string literals in places where Mailcore2 expects them to be double-quoted. (For example, in the text below, the subject is quoted but the sender name ProtonMail is not:
> 
> ```
> * 1 FETCH (UID 1 FLAGS (\\Seen \\Flagged nonjunk) ENVELOPE (\"Thu, 14 Dec 2017 11:50:32 -0800\" \"How to get help and support\" ((ProtonMail NIL support protonmail.ch)) ((ProtonMail NIL support protonmail.ch)) () ((NIL NIL bengotow protonmail.com)) () () \"\" \"\") BODY[HEADER.FIELDS (REFERENCES)] {539}\r\n
> ```
> 
> I was able to expand libetpan's `mailimap_quoted_parse` method to handle this scenario (just read until we reach a control character or space), and sync ProtonMail messages in to Mailspring. It looks like ProtonMail's IMAP interface makes really heavy use of "virtual folders", (#309, #304) and also doesn't have a synced IMAP Drafts folder, so there are some more todos before this will really work.

Any progress on this? :/

**Comment by romuloalves** [comment]
Bridge upgraded (macos) but still the same behaviour, it sends but can't download.

**Comment by kgoglin** [comment]
Also still not working on Linux with bridge upgrade. :(

**Comment by kevinsarsen** [comment]
Same issues here on Linux, latest bridge and latest Mailspring.

**Comment by forthommel** [comment]
> Same issues here on Linux, latest bridge and latest Mailspring.

+1

**Comment by apatil** [comment]
Same with Protonmail Bridge 1.1.3.

**Comment by chg20** [comment]
+1 happy to put a bounty on this issue

**Comment by gldtn** [comment]
Anyone reading this please vote at Proton mail uservoice platform to see if they can fix this issue:
https://protonmail.uservoice.com/forums/284483-feedback/suggestions/35701810-mailspring-support-for-protonmail-bridge

**Comment by edgyer** [comment]
Guys you reckon is best we put a bounty up like @chg20 suggested it has been literally years now... hope someone comes along and fix it.

**Comment by theVKC** [comment]
I've voted for this on the uservoice platform, and eagerly await deployment of this feature. Mailspring + ProtonMail = yay!

**Comment by FireFtw** [comment]
@edgyer have to agree, I feel like we won't see any movement from either side without some incentive if nobody has done it for years.

Is there some sort of cool crowdfunding bounty thing? I'll throw some money at it.

**Comment by FireFtw** [comment]
The answer is yes! Bounty started at
https://www.bountysource.com/issues/52600037-protonmail-bridge-imap-integration
@edgyer  @chg20 if you are still interested

**Comment by d2dyno** [comment]
Bumped it as well

**Comment by FaithLV** [comment]
Came looking for a solution. Sad that it's not been fixed for almost two years now :(

**Comment by odelucca** [comment]
No updates on this?

**Comment by LydiaUwU** [comment]
Checking back on this?

**Comment by molaeiali** [comment]
Problem of creating folders still exists on Bridge 1.2.5 and MailSpring 1.7.4, any updates?

**Comment by Siilwyn** [comment]
I just ran into this issue with a different cause, my SMTP settings were wrong. Protonmail uses a different port for sending emails compared to receiving. So make sure the ports in Thunderbird match those!

**Comment by mcrowson** [comment]
@Siilwyn did it work flawlessly for you after correcting the settings?

**Comment by Siilwyn** [comment]
@mcrowson yes!

**Comment by mcrowson** [comment]
Did you have to check `Allow Insecure SSL`?  on both IMAP and SMTP

**Comment by Siilwyn** [comment]
@mcrowson I had to accept insecure certs because they are local bridge certs if that's what you mean.

**Comment by mcrowson** [comment]
Still not working for me. Nothing in the logs either. I already have Gmail account in mind, trying to add the Proton Account. From the Accounts page i add it and it then acts like I've successfully added it, but the logs have no record of it and the account never appears.

**Comment by crashdump** [comment]
Not working for me either, with or without accepting insecure certs.

**Comment by mcrowson** [comment]
The bridge is open source now if this helps: https://github.com/ProtonMail/proton-bridge

**Comment by johackim** [comment]
When we run [proton-bridge](https://github.com/ProtonMail/proton-bridge) in cli with `make run` command, we can see errors : 

```
ERRO[Apr 22 16:56:04.397] Could not get mailbox error="mailbox Mailspring does not exist" name=Mailspring pkg=imap
ERRO[Apr 22 16:48:58.420] Could not get mailbox error="mailbox Mailspring/Snoozed does not exist" name=Mailspring/Snoozed pkg=imap
```

With Protonmail, directories are locate inside a "Folders" directory  and not on the root : 

![](https://i.imgur.com/rbuQbmY.png)

Is it possible to custom the path of "Mailspring" and "Mailspring/Snoozed" with mailspring ?

**Comment by bengotow** [comment]
Hey @johackim! I think that we can fix those errors on the Mailspring side (I know there's at least one other provider that doesn't allow the `/` in the path and needs a custom one too), but if IRC those errors aren't show-stoppers (though they do break Mailspring's Snooze feature). Does the bridge otherwise seem to work? I think back when this was opened, we were seeing all sorts of parsing errors trying to read the IMAP responses it forwarded.

**Comment by mannp** [comment]
Thanks for the support on this one; really hoping it can get resolved.

**Comment by t3pfaffe** [comment]
@bengotow no, it does not work in any fashion outside of recognizing the names of existing folders and getting stuck on "scanning messages" at 0%

**Comment by chg20** [comment]
ProtonMail bridge is now open source.  I have opened an issue up over there:

https://github.com/ProtonMail/proton-bridge/issues/33

**Comment by t3pfaffe** [comment]
We'll I think it is mostly clear that alot of the issues are on Mailsprings end so I dont know if bringing some of the discussion over to ProtonMail will help here

**Comment by freddiecoleman** [comment]
Also affected by this. I want to start using Mailspring because it seems great but this is a show stopper for me at the moment.

**Comment by t3pfaffe** [comment]
@freddiecoleman if you are using Linux, I find that Evolution serves as a much better (both function and form) email client compared to Thunderbird; considering that it follows your GTK theme. It is my backup to whenever Mailspring doesnt work.

**Comment by kemsar** [comment]
I've been trying Mailspring periodically for years now (ever since the ProtonMail Bridge was release) and I run into this issue every time. **How disappointing!** 

I can't imagine this is difficult to fix. There's already an option in "Preferences > Folders" to select which folders to use for "Inbox", "Sent Mail", etc. Why not "Mailspring"? I'd be happy to contribute if the sync engine was open sourced already.

```
188351 [2020-06-26 08:42:21.943] [main] [info] ------------- Starting Sync (*********@protonmail.com) ---------------
188351 [2020-06-26 08:42:21.948] [background] [info] Marking all folders as `busy`
188351 [2020-06-26 08:42:21.948] [background] [info] Syncing folder list...
188351 [2020-06-26 08:42:22.213] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorSubscribe
188351 [2020-06-26 08:42:22.555] [metadata] [info] Metadata delta stream starting...
188351 [2020-06-26 08:42:22.945] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorSubscribe
188351 [2020-06-26 08:42:22.954] [background] [info] Syncing folder list...
188351 [2020-06-26 08:42:22.962] [foreground] [info] Idling on folder INBOX
188351 [2020-06-26 08:42:23.207] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorSubscribe
188351 [2020-06-26 08:42:23.457] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorSubscribe
188351 [2020-06-26 08:42:23.462] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 201, Heavy: true
188351 [2020-06-26 08:42:23.492] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
***

188351 [2020-06-26 08:42:23.492] [background] [info] --sleeping
```

**Comment by rottenpants466** [comment]
Tried evolution and thunderbird but to be honest i find mailspring way more attractive and simpler to use (just switched to linux from windows, specificaly elementaryOS ). Like many others i tried using it but im getting nothing no emails/drats/etc...

It's a shame really

**Comment by jmichaelward** [comment]
Just attempted to give Mailspring a try this morning as I'm looking for other alternatives to Evolution, and I hit this same issue.

**Comment by anjoweichbrodt** [comment]
I would love to use Mailspring but the incompatibility with the ProtonMail Bridge are a no-go for me. Please fix this issues.

**Comment by t3pfaffe** [comment]
Alright I'm tired of just asking these already underpaid/overworked devs to do something for me for free. I added $100 to the bounty. I suggest you guys add something too. This is primarily a problem with Mailspring. It's unlikely that anyone but Foundry376 will be able to fix it so lets put up some cash and make it worthwhile for them. 

The bounty is currently at $260. My $100 expires in 3 months. 
https://www.bountysource.com/issues/52600037-protonmail-bridge-imap-integration

**Comment by mcrowson** [comment]
Threw $15 in, thanks for getting the ball rolling, hopefully others will throw in too so that this becomes a more compelling problem to solve.

**Comment by ploum** [comment]
Added 25$ myself. If everyone who took the time to subscribe to this issue added 15$, this could quickly become attractive.

**Comment by Amazong** [comment]
Chipped in with 15$ also! Thanks for the iniciative, t3pfaffe. Looking forward to seeing this solved.

**Comment by t3pfaffe** [comment]
I have been getting mild success (recieving working but not sending) on a fork of mailspring called [mailspring-libre](https://github.com/notpushkin/Mailspring-Libre). Its better than nothing but I believe it only supports Linux.

**Comment by ploum** [comment]
the mailspring-libre fork is an awesome idea. I think that the bounty could be claimed by mailspring-libre if they manage to solve this issue.

**Comment by mcrowson** [comment]
Looks like that project hasn't been active since May :(

**Comment by anjoweichbrodt** [comment]
Added 50$ as well.

**Comment by CaninoDev** [comment]
What about a "proxy" server? One that can act as a go between (locally installed of course) between ProtonMail Bridge and Mailspring. It can sanitize communication between both ends to get it to work.  Is this a feasible approach?

**Comment by dslul** [comment]
I would contribute a solution if only "mailsync" was opensource. I started working on an alternative backend that will be opensource but it's not ready yet.
For now, if you really want to use it with Protonmail, you can use the hydroxide bridge (also works with free protonmail accounts), but removing the All Mail folder that causes some problems.
```
git clone https://github.com/emersion/hydroxide.git
cd hydroxide
sed -i 's/\t{\"All Mail/\/\/&/' imap/user.go
GO111MODULE=on go build ./cmd/hydroxide
sudo cp hydroxide /usr/local/bin/hydroxide
```
You can then do hydroxide auth <username> to login, and add hydroxide serve to your startup scripts.

**Comment by alecbcs** [comment]
On the latest versions of the ProtonMail Bridge I've been able to sync, and send mail successfully through Mailspring. Well that is until Mailspring attempts to create its folders in the root directory and throws an error. @bengotow is the Mailspring folder creation something that is a part of Mailspring itself or Mailsync? With the addition of an automatic fall back system to create the folders in a subdirectory or by giving the user the option of folder location in the Mailspring config we might be able to close this issue relatively soon. I'm happy to help out any way I can if the code to help solve this problem is publicly accessible.

**Comment by exander77** [comment]
This is the MailSpring issue, but I could possibly fix their issue in Bridge, but it would need to be accepted by ProtonMail or you would need to use a custom build of Bridge. I modified Bridge to work with K-9 for example.

I do not like MailSpring, but if this would be an acceptable solution and you are willing to pay for it...

**Comment by ploum** [comment]
My contribution to the bounty would gladly go to the person fixing the issue in PM bridge instead of Mailspring.

**Comment by exander77** [comment]
> On the latest versions of the ProtonMail Bridge I've been able to sync, and send mail successfully through Mailspring. Well that is until Mailspring attempts to create its folders in the root directory and throws an error. @bengotow is the Mailspring folder creation something that is a part of Mailspring itself or Mailsync? With the addition of an automatic fall back system to create the folders in a subdirectory or by giving the user the option of folder location in the Mailspring config we might be able to close this issue relatively soon. I'm happy to help out any way I can if the code to help solve this problem is publicly accessible.

That part is deep in Mailsync which is closed source...

**Comment by exander77** [comment]
@ploum What OS do you use? Are you willing to beta test builds?

**Comment by exander77** [comment]
Is anybody willing to test the build?

**Comment by YoannMa** [comment]
@exander77 I would be willing to do beta testing if needed, I have both a windows and a linux (ubuntu flavor) setup

**Comment by exander77** [comment]
@YoannMa https://github.com/exander77/proton-bridge/releases/tag/mailspring-0

First try. I need anything which would seem out of the ordinary. I am not a Mailspring user. I tried Mailspring, it shows all folders, the unnecessary Folder prefix disappeared and no errors are present in the log now. Snoozed folder seems to be automatically created. Its location on the server is Folders/Snoozed.

**Comment by exander77** [comment]
Any other testers?

**Comment by YoannMa** [comment]
@exander77 I tried out without any issue, snoozing was working as well.

**Comment by lsnow99** [comment]
@exander77 I am testing on Linux with bleeding edge Mailspring. So far so good, and snoozing seems to work. I am running into an issue, however, where sometimes when returning to the Mailspring window all my emails are gone from the inbox (and it says "Hooray! You're done." when I am selected on the Inbox folder). I can see my emails in the All Mail section but not in the Inbox folder. Could it have something to do with my Inbox folder on protonmail.com being named INBOX instead of Inbox?

I can get the inbox folder to fix itself by doing File -> Sync New Mail Now. Alternatively, waiting a while seems to just resolve the issue (temporarily of course, until it reappears).

Anyone else running into this?

**Comment by exander77** [comment]
@exander77 Does this happens wich other mail provides?

**Comment by exander77** [comment]
@YoannMa Please report after more trying. Do you have the same problem as @lsnow99. I am not sure if it is ProtonMail related, his local issue or a general problem with MailSpring.

I think it would be pretty complicated to use custom build version. So I will try to push workaround into ProtonBridge official repo. Probably in a form of command-line option or type `--mailspring-workaround` or something like that.

**Comment by lsnow99** [comment]
@exander77 This was happening a few months ago as well with Mailspring on a separate computer I was using. I started following this GitHub issue in hopes the fix to protonmail bridge would fix it. It only happens with my protonmail account. (I have a few gmail and one outlook.com accounts that don't have this issue in Mailspring). I don't see anything relevant in the logs. I might try using a different protonmail account to see if it persists there as well.

**Comment by exander77** [comment]
@lsnow99 Try that and I will try to reproduce myself.

**Comment by lsnow99** [comment]
@exander77 Just upgraded a different account for the month for testing and it is having the same issue. Let me know if the issue appears on your account.

**Comment by exander77** [comment]
@lsnow99 It seems to happen for me as well, from time to time, folder contents disappear, but I can press F5 and they reload. But there is literally nothing related to this in low. No warning, no error. And info messages do not seem to relate.

**Comment by lsnow99** [comment]
@exander77 Yup that's where I'm at. I'm not sure if fixing that falls under the scope of this ticket or a different one. It does seem to be a protonmail specific incompatibility, however. I also don't know if it can really be addressed without digging into Mailsync which unfortunately seems to be closed source :(

**Comment by exander77** [comment]
@lsnow99 I try to debug it a little, but I have only communication that goes on with Bridge and logs from Mailspring. I hat Foundry376 that that didn't make Mailsync OpenSource.

Also, their reasoning is total BS:
https://github.com/Foundry376/Mailspring/blob/master/ROADMAP.md#why-is-mailsync-closed-source

All issues could have been easily fixed if it were OpenSource.

I worry it is using either some proprietary code which they do not have rights to use, or it is doing some BS they don't to be public.

**Comment by lsnow99** [comment]
Yup. It's looking like I won't continue to use Mailspring unless they open-source Mailsync. Right now mailsync is eating up my CPU in the background- I don't see why it needs to do all this processing if it just needs to sync mail. And considering it doesn't seem compatible with Protonmail, It's looking like I will need to find a new application. Thanks for your help fixing this issue @exander77 .

**Comment by exander77** [comment]
@lsnow99 There a fork of this project Mailspring Libre, which want to remove anything closed including mailsync, but it will take some time.

**Comment by t3pfaffe** [comment]
And now this thread has gone full circle lol.

**Comment by exander77** [comment]
@t3pfaffe I have said it in the beginning that this is Mailsping project issue, not the ProtonBridge issue. If devs were to share sources, I can fix it, I a am not at all worried that we would not figure out how to build it.

I also toyed with the idea to fix it in Mailsync binary. I could rewire Mailspring/Snoozed into Folders/Snoozed. It sounds a bit extreme, but as the mailsync is not updated at all. The problem is that the binary has a lot of occurrences of Mailspring, so I would need to carefully check if that occurrence is relevant. But Mailspring is shorted string than Folders and this should be doable without significant matching.

**Comment by forthommel** [comment]
> Yup. It's looking like I won't continue to use Mailspring unless they open-source Mailsync. Right now mailsync is eating up my CPU in the background- I don't see why it needs to do all this processing if it just needs to sync mail. And considering it doesn't seem compatible with Protonmail, It's looking like I will need to find a new application. Thanks for your help fixing this issue @exander77 .

Sad but absolutely true. Same action for me, will wait for Mailspring Libre to be in an usable state and give up any hope for Mailspring unless any open source release of Mailsync is expected.

**Comment by CodeMouse92** [comment]
Great news everyone! **Mailsync is now open source!** 🎉 🎉 🎉

Read more here: https://community.getmailspring.com/t/a-free-open-source-future-for-mailspring/484

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/protonmail-bridge-imap/485

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@stellarsquall: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
