### ISSUE TITLE
Bug: Signature not changing when picking different sender address

### ISSUE THREAD

**Issue by enoversum** [Foundry376/Mailspring#570]
In the latest version (at least on Windows), when you follow a mailto: link and change your sender's address, the signature of the automatically chosen sender's account is still implemented and doesn't change to the newly picked account.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - will get this fixed in the next release.

**Comment by enoversum** [comment]
Hi @bengotow , the changelog doesn't mention it, and sometimes it works, sometimes it doesn't, so it's not fixed as of yet, is it 😄 ?

**Comment by bengotow** [comment]
Hey! Unfortunately this didn't make the cut for today's release, but it's fixed by 8861fa50a866d86eaa13953fb532d94ce1e52b96 - stay tuned :-)

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.
