### ISSUE TITLE
Mail rules not triggering automatically

### ISSUE THREAD

**Issue by agurodriguez** [Foundry376/Mailspring#59]
They work properly if you hit the button `Process entire inbox`

<img width="857" alt="screen shot 2017-10-06 at 7 39 38 pm" src="https://user-images.githubusercontent.com/13837769/31301123-218f84b8-aace-11e7-837c-910b7db66680.png">

---

##### Are there any related issues?

No

##### What operating system are you using?
macOS Sierra 10.12.6

##### What version of Mailspring are you using?
1.0.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

**Comment by oxysoft** [comment]
Same problem here on Windows 10, very important feature that needs fixing ASAP.

**Comment by bengotow** [comment]
Hey! Been working on this today - it should be fixed in the next release by 1950f5b3569b5a3c188dfb90d66b3e63e5248ef5.

**Comment by agurz** [comment]
Hi @bengotow, I can confirm this is fixed in 1.0.6 release

**Comment by oxysoft** [comment]
@bengotow It seems to work most of the time now, however I still see some messages that don't get moved, and I know my rule works because it DOES get moved properly when I trigger it manually.

**Comment by Tera3yte** [comment]
Same Problem here, installed it via `snapd` on Linux Mint, my rules does not work automatically, I always need to trigger them manual. Maybe somebody can check this again

**Comment by chrisbjr** [comment]
Experiencing this problem in v1.2.1 in MacOS High Sierra

**Comment by nico81** [comment]
Same problem here, very annoying:
Windows 10
IMAP Account
Version 1.4.2
No third party plugin

**Comment by weskoerber** [comment]
Mail rules don't trigger until I manually process the entire inbox on Windows 10 x64.

**Comment by rwdim** [comment]
Same here as of right now, Ubuntu 18.04.1LTS, MailSpring 1.5.5-b7939d38, rules NOT auto-running, but they do run if I manually run them.

**Comment by Sjonnie404** [comment]
I'm having the same issue on Ubuntu 18.04 LTS, MailSpring 1.5.5-b7939d38. It doesn't apply them automatically, but they do manually. Hope this can be fixed soon.

**Comment by lots0logs** [comment]
@bengotow Can we reopen this issue? Its clearly still affecting people (myself included).

**Comment by oxysoft** [comment]
No disrespect meant to the author of this project, I know full well tenacious some bugs can be and Mailspring is still awesome, BUT how hard can it be to run some mail rules on arriving messages?!? The issue was resolved for a while but I noticed it again recently. If I look in my labels, no new messages were put there after December 30. Windows 10 x64.

**Comment by quixoticraindrp** [comment]
This issue is still present in Mailspring 1.5.7-2057ca30 on macOS 10.14.3 connecting to iCloud.

No mail rules trigger when matching emails enter the inbox with Mailspring already running. No mail rules trigger when opening Mailspring, and matching emails are in the inbox (but have not yet been seen by Mailspring, having arrived while Mailspring was not running).

Rules work as expected when triggered manually.

I don't yet know if this issue also affects Gmail accounts, as the Mail Rule creation system is b0rked and creating new mail rules is extremely tedious, so I haven't even tried.

**Comment by bengotow** [comment]
Hey folks! Will take a look at this and see what's going on -

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
