### ISSUE TITLE
Cannot view a particular message thread

### ISSUE THREAD

**Issue by JimSangwine** [Foundry376/Mailspring#611]
##### What operating system are you using?
Ubuntu 17.10 running i3wm

##### What version of Mailspring are you using?
1.1.2-8ae17eae

--

**Bug?**

One particular message thread suddenly won't display. It did to begin with, and then it died so I suspect it might have been some metadata added in / by Mailspring? The thread still works fine in Gmail and I've replied to it there in the hope that it would fix the problem in Mailspring. No such luck. 

Here is everything I managed to copy from the error trace:

```
TypeError: Cannot read property 'nodes' of undefined
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:114:11)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at Changes.normalizeNodeByKey (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:54:3)
    at Change.call (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:197:10)
    at Change.(anonymous function) [as normalizeNodeByKey] (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:262:15)
    at Changes.normalizeDocument (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:37:10)
    at Change.call (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:197:10)
    at Change.(anonymous function) [as normalizeDocument] (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:262:15)
    at Changes.normalize (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:24:10)
    at Change.call (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:197:10)
    at Change.(anonymous function) [as normalize] (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:262:15)
    at Object.onChange (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/plugins/before.js:137:67)
    at Stack.run (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/stack.js:187:38)
    at new Editor (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/editor.js:118:11)
    at constructClassInstance (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:109:354)
    at beginWork (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:440)
    at d (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:161:93)
    at f (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:161:417)
    at g (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:162:149)
    at m (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:173)
    at w (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at z (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at u (/snap/mailspring/140/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.mi
```

##### Do you have any third-party plugins installed? If so, which ones?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Sorry, I don't know how to reproduce this.

--

**Comment by bengotow** [comment]
Wow this is an interesting one - thanks for reporting this, This /should/ be fixed by the changes in 835ad95efc0cc69d9b8fb98f401853e8944bfbaf, which prevent this code from running in `slate`. I'm going to mark this as closed by that commit, but I'll leave it open for a bit to be sure we don't see any more occurrences.

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.

**Comment by JimSangwine** [comment]
Hi @bengotow 

I'm still seeing the error (or one similar) in the same thread:

```
TypeError: Cannot read property 'nodes' of undefined
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:114:11)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at _loop (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:100:7)
    at normalizeNodeAndChildren (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:122:5)
    at Changes.normalizeNodeByKey (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:54:3)
    at Change.call (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:197:10)
    at Change.(anonymous function) [as normalizeNodeByKey] (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:262:15)
    at Changes.normalizeDocument (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:37:10)
    at Change.call (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:197:10)
    at Change.(anonymous function) [as normalizeDocument] (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:262:15)
    at Changes.normalize (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/changes/with-schema.js:24:10)
    at Change.call (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:197:10)
    at Change.(anonymous function) [as normalize] (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/change.js:262:15)
    at Object.onChange (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/plugins/before.js:137:67)
    at Stack.run (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate/lib/models/stack.js:187:38)
    at new Editor (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/editor.js:118:11)
    at constructClassInstance (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:109:354)
    at beginWork (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:440)
    at d (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:161:93)
    at f (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:161:417)
    at g (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:162:149)
    at m (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:173)
    at w (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at z (/snap/mailspring/167/usr/share/mailspring/resources/app
```

MailSpring version: 1.1.3-27dcee2f
