### ISSUE TITLE
Moving cursor up/down with arrow keys

### ISSUE THREAD

**Issue by intradesign** [Foundry376/Mailspring#727]
Moving cursor up/down with arrow keys is not working when the cursor is positioned at the end of formatted text. Moving it left/right works.

**Example:**
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, **sed diam voluptua:**
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

**Following happens:** When the cursor is behind the colon I cannot move it up or down. I have to go one step back or forward and then move the cursor up or down.

**Comment by bengotow** [comment]
I've been able to reproduce this - it seems like a Slate error. I'll keep an eye on their bug tracker and see if there's a fix for this in the works already.

**Comment by xclabit** [comment]
I have reproduced this as well and after reading @spalaciob's comment, I tried experimenting this behavior (unfortunately while writing a lengthy reply... good thing there was a draft saved) by typing `:)` and pressing up/down to see what happens... seems nothing happens, the cursor doesn't move.

However, if I move the cursor between the colon and the parenthesis (pressing left arrow one time) and then push up or down, I lose the message composition editor and I get the following crash error in the editor pane:
```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).
    at findDOMRange (C:\Users\user\AppData\Local\Mailspring\app-1.5.5\resources\app.asar\node_modules\slate-react\lib\utils\find-dom-range.js:37:5)
    at Content._this.updateSelection (C:\Users\user\AppData\Local\Mailspring\app-1.5.5\resources\app.asar\node_modules\slate-react\lib\components\content.js:154:46)
    at Content._this.componentDidUpdate (C:\Users\user\AppData\Local\Mailspring\app-1.5.5\resources\app.asar\node_modules\slate-react\lib\components\content.js:121:13)
    at Hi (C:\Users\user\AppData\Local\Mailspring\app-1.5.5\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:227:383)
    at Fi (C:\Users\user\AppData\Local\Mailspring\app-1.5.5\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:218:212)
    at Gi (C:\Users\user\AppData\Local\Mailspring\app-1.5.5\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:217:174)
    at Ki (C:\Users\user\AppData\Local\Mailspring\app-1.5.5\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:232:135)
    at de (C:\Users\user\AppData\Local\Mailspring\app-1.5.5\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:85:207)
```
Wasn't clear what happened exactly but at first it almost looked like I lost my draft, but somehow I got it to re-appear again. Tried replicating the problem in a test reply and was able to reproduce the above but whether or not the draft saved was inconsistent, this could be a potential area for lost work (really critical issue here). 

I'm losing faith in this e-mail client. I hope the problems get sorted out, especially major issues such as this one, and https://github.com/Foundry376/Mailspring/issues/304. But if localization and theme galleries are the recent focus of development, I can't see how any paid user will be happy with this software.

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Comment by thomasjonas** [comment]
Did this bug came back? I've noticed similar behaviour and @intradesign's example still/again shows the bug. I'm on Mailspring 1.7.5-a976d710.

**Comment by lucaspar** [comment]
Still an issue in v1.8.0...

Up/down arrows often don't work around formatted text.

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@lucaspar: Can you please open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team
