### ISSUE TITLE
Spell check suggestions broken?

### ISSUE THREAD

**Issue by danawoodman** [Foundry376/Mailspring#747]
##### Are there any related issues?

Not that I see

##### What operating system are you using?

OSX

##### What version of Mailspring are you using?

Latest

##### Do you have any third-party plugins installed? If so, which ones?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I am no longer seeing spelling suggestions when right clicking. Is this behavior broken now or is there sometime wrong with my local install?

![](https://cl.ly/q2sC/Screen%20Recording%202018-03-08%20at%2001.29%20PM.gif)

**Comment by fcastilloec** [comment]
I can confirm this problem on my end. I'm using Ubuntu 16.04 so it seems to be related to the fix for #677 which you previously reported.
Hopefully, they are as fast as fixing this issue as they were for the other one.

**Comment by harm0nic** [comment]
I would like to confirm the same issue on Ubuntu 17.10

**Comment by danawoodman** [comment]
You're right @fcastilloec, nice to know. Still would consider this "broken" however since that isn't obvious (right clicking should work too)

**Comment by bengotow** [comment]
Hey! I was able to reproduce this using @fcastilloec's example—it turns out I was control-clicking on my Mac (since it doesn't have a right mouse button) and it actually produces a different JavaScript event than right-clicking. Should be fixed in 818d02fa359cd38bac644f4071f3eddf74e40b39. I'm prepping a patch release right now to fix a few other issues, so this will go out very soon!

**Comment by farfromrefug** [comment]
@bengotow it still doesn't always work. Do a right click on a word you get the right menu, immediatly do the right click on another word you get the same menu and not the one for the second word.
Tried with the github version i build

**Comment by fcastilloec** [comment]
The original bug was resolved, but there's something weird going on. To better explain what @farfromrefug said, here's an animation:
![mailspring](https://user-images.githubusercontent.com/1280530/38379690-7cbdc52c-38cf-11e8-8ca4-ca1d2d1fac8b.gif)

**Comment by bengotow** [comment]
Hey folks—this shipped in version 1.3.0. The app should have auto-updated by now, but if not you can download the latest release from https://www.getmailspring.com/download. Enjoy!
